// Cloudflare entry point: the OpenNext app plus the Cron Trigger that runs
// the scheduled sweep (POST /api/bos/cron with CRON_SECRET).
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

interface Env {
  CRON_SECRET?: string;
  ADMIN_URL?: string;
}

const worker = {
  fetch: handler.fetch,

  async scheduled(_event: unknown, env: Env, ctx: { waitUntil(p: Promise<unknown>): void }) {
    if (!env.CRON_SECRET || !env.ADMIN_URL) return;
    const req = new Request(`${env.ADMIN_URL.replace(/\/$/, "")}/api/bos/cron`, { method: "POST", headers: { authorization: `Bearer ${env.CRON_SECRET}` } });
    ctx.waitUntil(handler.fetch(req, env, ctx));
  },
};

export default worker;
