// Display labels (Arabic-first, matching the existing admin) and status
// tones for StatusBadge. One place so every module shows statuses the same way.

export type Tone = "neutral" | "info" | "success" | "warning" | "danger" | "accent";

interface StatusDef {
  label: string;
  tone: Tone;
}

type StatusMap = Record<string, StatusDef>;

export const statusMaps: Record<string, StatusMap> = {
  stage_category: {
    open: { label: "مفتوحة", tone: "info" },
    won: { label: "مكسوبة", tone: "success" },
    lost: { label: "خاسرة", tone: "danger" },
  },
  priority: {
    low: { label: "منخفضة", tone: "neutral" },
    medium: { label: "متوسطة", tone: "info" },
    high: { label: "عالية", tone: "warning" },
    urgent: { label: "عاجلة", tone: "danger" },
  },
  activity_status: {
    pending: { label: "قيد الانتظار", tone: "neutral" },
    in_progress: { label: "قيد التنفيذ", tone: "info" },
    completed: { label: "مكتمل", tone: "success" },
    cancelled: { label: "ملغي", tone: "neutral" },
    overdue: { label: "متأخر", tone: "danger" },
  },
  task_status: {
    pending: { label: "قيد الانتظار", tone: "neutral" },
    in_progress: { label: "قيد التنفيذ", tone: "info" },
    blocked: { label: "متوقف", tone: "warning" },
    completed: { label: "مكتملة", tone: "success" },
    cancelled: { label: "ملغاة", tone: "neutral" },
    overdue: { label: "متأخرة", tone: "danger" },
  },
  activity_type: {
    call: { label: "مكالمة", tone: "neutral" },
    email: { label: "بريد", tone: "neutral" },
    whatsapp: { label: "واتساب", tone: "neutral" },
    linkedin: { label: "لينكدإن", tone: "neutral" },
    meeting: { label: "اجتماع", tone: "neutral" },
    follow_up: { label: "متابعة", tone: "neutral" },
    task: { label: "مهمة", tone: "neutral" },
    note: { label: "ملاحظة", tone: "neutral" },
    internal: { label: "داخلي", tone: "neutral" },
    client_communication: { label: "تواصل مع العميل", tone: "neutral" },
  },
  meeting_status: {
    scheduled: { label: "مجدول", tone: "info" },
    completed: { label: "تم", tone: "success" },
    cancelled: { label: "ملغي", tone: "neutral" },
    no_show: { label: "لم يحضر", tone: "warning" },
  },
  account_status: {
    prospect: { label: "محتمل", tone: "neutral" },
    active: { label: "نشط", tone: "success" },
    inactive: { label: "غير نشط", tone: "warning" },
    churned: { label: "منقطع", tone: "danger" },
  },
  deal_payment_status: {
    unpaid: { label: "غير مدفوعة", tone: "neutral" },
    partially_paid: { label: "مدفوعة جزئياً", tone: "warning" },
    paid: { label: "مدفوعة", tone: "success" },
  },
  proposal_status: {
    draft: { label: "مسودة", tone: "neutral" },
    ready: { label: "مراجعة داخلية", tone: "info" },
    published: { label: "مُرسل", tone: "accent" },
    viewed: { label: "تمت المشاهدة", tone: "info" },
    accepted: { label: "مقبول", tone: "success" },
    rejected: { label: "مرفوض", tone: "danger" },
    expired: { label: "منتهي", tone: "warning" },
  },
  contract_status: {
    draft: { label: "مسودة", tone: "neutral" },
    sent: { label: "مُرسل", tone: "accent" },
    viewed: { label: "تمت المشاهدة", tone: "info" },
    partially_signed: { label: "موقّع جزئياً", tone: "warning" },
    signed: { label: "موقّع", tone: "success" },
    expired: { label: "منتهي", tone: "warning" },
    cancelled: { label: "ملغي", tone: "neutral" },
  },
  invoice_status: {
    draft: { label: "مسودة", tone: "neutral" },
    sent: { label: "مُرسلة", tone: "accent" },
    partially_paid: { label: "مدفوعة جزئياً", tone: "warning" },
    paid: { label: "مدفوعة", tone: "success" },
    overdue: { label: "متأخرة", tone: "danger" },
    cancelled: { label: "ملغاة", tone: "neutral" },
  },
  payment_status: {
    pending: { label: "قيد الانتظار", tone: "neutral" },
    processing: { label: "قيد المعالجة", tone: "info" },
    completed: { label: "مكتملة", tone: "success" },
    failed: { label: "فشلت", tone: "danger" },
    refunded: { label: "مستردة", tone: "warning" },
  },
  payment_method: {
    bank_transfer: { label: "تحويل بنكي", tone: "neutral" },
    card: { label: "بطاقة", tone: "neutral" },
    cash: { label: "نقداً", tone: "neutral" },
    paypal: { label: "PayPal", tone: "neutral" },
    stripe: { label: "Stripe", tone: "neutral" },
    wise: { label: "Wise", tone: "neutral" },
    instapay: { label: "InstaPay", tone: "neutral" },
    vodafone_cash: { label: "Vodafone Cash", tone: "neutral" },
    other: { label: "أخرى", tone: "neutral" },
  },
  commission_status: {
    pending: { label: "قيد الانتظار", tone: "neutral" },
    eligible: { label: "مستحقة", tone: "info" },
    approved: { label: "معتمدة", tone: "accent" },
    paid: { label: "مدفوعة", tone: "success" },
    cancelled: { label: "ملغاة", tone: "neutral" },
  },
  commission_trigger: {
    deal_won: { label: "عند كسب الصفقة", tone: "neutral" },
    contract_signed: { label: "عند توقيع العقد", tone: "neutral" },
    payment_collected: { label: "عند تحصيل الدفعات (نسبي)", tone: "neutral" },
    full_payment: { label: "عند السداد الكامل", tone: "neutral" },
    milestone_payment: { label: "عند دفعة مرحلة", tone: "neutral" },
  },
  schedule_status: {
    scheduled: { label: "مجدولة", tone: "neutral" },
    invoiced: { label: "مفوترة", tone: "info" },
    paid: { label: "مدفوعة", tone: "success" },
    cancelled: { label: "ملغاة", tone: "neutral" },
  },
  approval_status: {
    pending: { label: "بانتظار القرار", tone: "warning" },
    approved: { label: "موافق عليه", tone: "success" },
    rejected: { label: "مرفوض", tone: "danger" },
    cancelled: { label: "ملغي", tone: "neutral" },
    superseded: { label: "استُبدل بنسخة أحدث", tone: "neutral" },
    changes_requested: { label: "مطلوب تعديلات", tone: "info" },
  },
  simple_approval: {
    pending: { label: "بانتظار الموافقة", tone: "warning" },
    approved: { label: "موافق عليه", tone: "success" },
    rejected: { label: "مرفوض", tone: "danger" },
    cancelled: { label: "ملغي", tone: "neutral" },
  },
  project_status: {
    planning: { label: "تخطيط", tone: "neutral" },
    design: { label: "تصميم", tone: "info" },
    development: { label: "تطوير", tone: "info" },
    qa: { label: "اختبار الجودة", tone: "info" },
    client_review: { label: "مراجعة العميل", tone: "accent" },
    launch: { label: "إطلاق", tone: "accent" },
    completed: { label: "مكتمل", tone: "success" },
    on_hold: { label: "معلّق", tone: "warning" },
    cancelled: { label: "ملغي", tone: "neutral" },
  },
  project_health: {
    healthy: { label: "سليم", tone: "success" },
    at_risk: { label: "معرّض للخطر", tone: "warning" },
    delayed: { label: "متأخر", tone: "danger" },
  },
  milestone_status: {
    not_started: { label: "لم تبدأ", tone: "neutral" },
    in_progress: { label: "قيد التنفيذ", tone: "info" },
    blocked: { label: "متوقفة", tone: "warning" },
    completed: { label: "مكتملة", tone: "success" },
  },
  change_request_status: {
    requested: { label: "مطلوب", tone: "neutral" },
    assessment: { label: "تقييم", tone: "info" },
    proposal: { label: "عرض", tone: "info" },
    client_approval: { label: "بانتظار موافقة العميل", tone: "warning" },
    approved: { label: "موافق عليه", tone: "accent" },
    added_to_project: { label: "أضيف للمشروع", tone: "success" },
    rejected: { label: "مرفوض", tone: "danger" },
  },
  issue_status: {
    open: { label: "مفتوحة", tone: "warning" },
    in_progress: { label: "قيد المعالجة", tone: "info" },
    resolved: { label: "محلولة", tone: "success" },
    closed: { label: "مغلقة", tone: "neutral" },
  },
  severity: {
    low: { label: "منخفضة", tone: "neutral" },
    medium: { label: "متوسطة", tone: "info" },
    high: { label: "عالية", tone: "warning" },
    critical: { label: "حرجة", tone: "danger" },
    trivial: { label: "بسيطة", tone: "neutral" },
    minor: { label: "ثانوية", tone: "info" },
    major: { label: "كبيرة", tone: "warning" },
  },
  employee_lifecycle_status: {
    candidate: { label: "مرشح", tone: "neutral" },
    hired: { label: "تم التعيين", tone: "info" },
    pending_onboarding: { label: "بانتظار التهيئة", tone: "warning" },
    onboarding: { label: "قيد التهيئة", tone: "info" },
    active: { label: "نشط", tone: "success" },
    on_leave: { label: "في إجازة", tone: "accent" },
    suspended: { label: "موقوف", tone: "danger" },
    offboarding: { label: "إنهاء خدمة", tone: "warning" },
    terminated: { label: "منتهي الخدمة", tone: "danger" },
    archived: { label: "مؤرشف", tone: "neutral" },
  },
  employment_type: {
    full_time: { label: "دوام كامل", tone: "neutral" },
    part_time: { label: "دوام جزئي", tone: "neutral" },
    contractor: { label: "متعاقد", tone: "neutral" },
    intern: { label: "متدرب", tone: "neutral" },
    freelancer: { label: "مستقل", tone: "neutral" },
  },
  attendance_status: {
    present: { label: "حاضر", tone: "success" },
    late: { label: "متأخر", tone: "warning" },
    absent: { label: "غائب", tone: "danger" },
    half_day: { label: "نصف يوم", tone: "warning" },
    leave: { label: "إجازة", tone: "accent" },
    holiday: { label: "عطلة", tone: "neutral" },
    overtime: { label: "عمل إضافي", tone: "info" },
    remote: { label: "عن بُعد", tone: "success" },
    on_break: { label: "في استراحة", tone: "info" },
    day_off: { label: "يوم راحة", tone: "neutral" },
    not_clocked_in: { label: "لم يسجل الحضور", tone: "neutral" },
  },
  overtime_status: {
    pending: { label: "بانتظار المراجعة", tone: "warning" },
    approved: { label: "معتمد", tone: "success" },
    rejected: { label: "مرفوض", tone: "danger" },
  },
  compensation_status: {
    pending: { label: "بانتظار التعويض", tone: "warning" },
    paid: { label: "مدفوع", tone: "success" },
    time_off: { label: "إجازة تعويضية", tone: "accent" },
    not_applicable: { label: "لا ينطبق", tone: "neutral" },
  },
  review_status: {
    draft: { label: "مسودة", tone: "neutral" },
    submitted: { label: "بانتظار اطلاع الموظف", tone: "warning" },
    acknowledged: { label: "تم الاطلاع", tone: "success" },
  },
  device_condition: {
    new: { label: "جديد", tone: "success" },
    good: { label: "جيد", tone: "success" },
    fair: { label: "مقبول", tone: "warning" },
    poor: { label: "ضعيف", tone: "warning" },
    damaged: { label: "تالف", tone: "danger" },
  },
  device_type: {
    laptop: { label: "لابتوب", tone: "neutral" },
    desktop: { label: "كمبيوتر مكتبي", tone: "neutral" },
    monitor: { label: "شاشة", tone: "neutral" },
    mobile: { label: "هاتف", tone: "neutral" },
    tablet: { label: "تابلت", tone: "neutral" },
    headset: { label: "سماعة", tone: "neutral" },
    office_equipment: { label: "معدات مكتبية", tone: "neutral" },
    software_license: { label: "ترخيص برنامج", tone: "info" },
    loanable: { label: "أصل للإعارة", tone: "neutral" },
    spare_part: { label: "قطع غيار ومخزون", tone: "neutral" },
    other: { label: "أخرى", tone: "neutral" },
  },
  return_status: {
    not_applicable: { label: "—", tone: "neutral" },
    pending_return: { label: "بانتظار الاسترجاع", tone: "warning" },
    returned: { label: "تم الاسترجاع", tone: "success" },
  },
  correction_status: {
    pending: { label: "بانتظار المراجعة", tone: "warning" },
    approved: { label: "موافق عليه", tone: "success" },
    rejected: { label: "مرفوض", tone: "danger" },
  },
  leave_status: {
    pending: { label: "بانتظار المراجعة", tone: "warning" },
    approved: { label: "موافق عليها", tone: "success" },
    rejected: { label: "مرفوضة", tone: "danger" },
    cancelled: { label: "ملغاة", tone: "neutral" },
  },
  mfa_status: {
    required: { label: "مطلوب", tone: "warning" },
    not_configured: { label: "غير مفعّل", tone: "danger" },
    pending: { label: "قيد الإعداد", tone: "warning" },
    enabled: { label: "مفعّل", tone: "success" },
    disabled: { label: "معطّل", tone: "danger" },
    recovery_required: { label: "يتطلب استرداد", tone: "danger" },
  },
  access_status: {
    not_started: { label: "لم يبدأ", tone: "neutral" },
    requested: { label: "مطلوب", tone: "info" },
    pending: { label: "قيد التنفيذ", tone: "warning" },
    provisioned: { label: "تم التجهيز", tone: "accent" },
    active: { label: "نشط", tone: "success" },
    rejected: { label: "مرفوض", tone: "danger" },
    revoked: { label: "مسحوب", tone: "danger" },
    expired: { label: "منتهي", tone: "warning" },
  },
  device_status: {
    purchased: { label: "تم الشراء", tone: "info" },
    in_stock: { label: "متاح", tone: "neutral" },
    assigned: { label: "مسلّم", tone: "success" },
    in_repair: { label: "في الصيانة", tone: "warning" },
    retired: { label: "مستبعد", tone: "neutral" },
    lost: { label: "مفقود", tone: "danger" },
  },
  device_security_status: {
    compliant: { label: "متوافق", tone: "success" },
    warning: { label: "تحذير", tone: "warning" },
    non_compliant: { label: "غير متوافق", tone: "danger" },
    unknown: { label: "غير معروف", tone: "neutral" },
  },
  ticket_status: {
    open: { label: "مفتوحة", tone: "warning" },
    in_progress: { label: "قيد المعالجة", tone: "info" },
    waiting_for_client: { label: "بانتظار العميل", tone: "accent" },
    resolved: { label: "محلولة", tone: "success" },
    closed: { label: "مغلقة", tone: "neutral" },
  },
  bug_status: {
    reported: { label: "مُبلّغ", tone: "neutral" },
    triaged: { label: "مفروز", tone: "info" },
    in_progress: { label: "قيد الإصلاح", tone: "info" },
    ready_for_qa: { label: "جاهز للاختبار", tone: "accent" },
    qa: { label: "قيد الاختبار", tone: "accent" },
    fixed: { label: "تم الإصلاح", tone: "success" },
    closed: { label: "مغلق", tone: "neutral" },
  },
  feature_request_status: {
    requested: { label: "مطلوبة", tone: "neutral" },
    review: { label: "قيد المراجعة", tone: "info" },
    approved: { label: "موافق عليها", tone: "accent" },
    rejected: { label: "مرفوضة", tone: "danger" },
    planned: { label: "مخطط لها", tone: "info" },
    in_development: { label: "قيد التطوير", tone: "info" },
    released: { label: "تم الإطلاق", tone: "success" },
  },
  onboarding_status: {
    in_progress: { label: "قيد التنفيذ", tone: "info" },
    completed: { label: "مكتملة", tone: "success" },
    cancelled: { label: "ملغاة", tone: "neutral" },
  },
  kb_status: {
    draft: { label: "مسودة", tone: "neutral" },
    published: { label: "منشور", tone: "success" },
    archived: { label: "مؤرشف", tone: "neutral" },
  },
  automation_run_status: {
    running: { label: "قيد التشغيل", tone: "info" },
    success: { label: "نجح", tone: "success" },
    failed: { label: "فشل", tone: "danger" },
    skipped: { label: "لم تنطبق الشروط", tone: "neutral" },
  },
  probation_status: {
    none: { label: "لا يوجد", tone: "neutral" },
    in_probation: { label: "تحت الاختبار", tone: "warning" },
    passed: { label: "اجتاز فترة الاختبار", tone: "success" },
    extended: { label: "تمديد فترة الاختبار", tone: "warning" },
    failed: { label: "لم يجتز", tone: "danger" },
  },
  employee_contract_status: {
    draft: { label: "مسودة", tone: "neutral" },
    pending_signature: { label: "بانتظار التوقيع", tone: "warning" },
    active: { label: "ساري", tone: "success" },
    expired: { label: "منتهي", tone: "danger" },
    terminated: { label: "مُنهى", tone: "danger" },
    superseded: { label: "مستبدل بنسخة أحدث", tone: "neutral" },
    cancelled: { label: "ملغي", tone: "neutral" },
  },
  employee_contract_type: {
    employment: { label: "عقد عمل", tone: "neutral" },
    renewal: { label: "تجديد", tone: "info" },
    amendment: { label: "ملحق تعديل", tone: "accent" },
    probation: { label: "فترة اختبار", tone: "warning" },
    freelance: { label: "عمل حر", tone: "neutral" },
    internship: { label: "تدريب", tone: "neutral" },
    nda: { label: "اتفاقية سرية", tone: "neutral" },
    other: { label: "أخرى", tone: "neutral" },
  },
  signature_status: {
    pending: { label: "بانتظار التوقيع", tone: "warning" },
    employee_signed: { label: "وقّع الموظف", tone: "info" },
    company_signed: { label: "وقّعت الشركة", tone: "info" },
    signed: { label: "موقّع", tone: "success" },
  },
  document_status: {
    pending_verification: { label: "بانتظار التحقق", tone: "warning" },
    valid: { label: "ساري", tone: "success" },
    rejected: { label: "مرفوض", tone: "danger" },
    expired: { label: "منتهي", tone: "danger" },
    archived: { label: "مؤرشف", tone: "neutral" },
  },
  document_category: {
    identity: { label: "هوية", tone: "neutral" },
    employment: { label: "توظيف وعقود", tone: "neutral" },
    qualification: { label: "مؤهلات", tone: "neutral" },
    finance: { label: "مالية وبنوك", tone: "neutral" },
    insurance: { label: "تأمينات", tone: "neutral" },
    tax: { label: "ضرائب", tone: "neutral" },
    medical: { label: "طبي", tone: "neutral" },
    performance: { label: "أداء", tone: "neutral" },
    disciplinary: { label: "تأديبي", tone: "neutral" },
    payroll: { label: "رواتب", tone: "neutral" },
    other: { label: "أخرى", tone: "neutral" },
  },
  payroll_run_status: {
    draft: { label: "مسودة", tone: "neutral" },
    calculated: { label: "محسوب", tone: "info" },
    pending_approval: { label: "بانتظار الاعتماد", tone: "warning" },
    approved: { label: "معتمد", tone: "success" },
    paid: { label: "مدفوع", tone: "success" },
    cancelled: { label: "ملغي", tone: "neutral" },
  },
  payroll_run_type: {
    regular: { label: "دورة شهرية", tone: "neutral" },
    off_cycle: { label: "خارج الدورة", tone: "accent" },
    final_settlement: { label: "تسوية نهائية", tone: "warning" },
  },
  payslip_status: {
    draft: { label: "مسودة", tone: "neutral" },
    final: { label: "نهائية", tone: "info" },
    paid: { label: "مدفوعة", tone: "success" },
    void: { label: "ملغاة", tone: "neutral" },
  },
  bonus_status: {
    pending: { label: "بانتظار الاعتماد", tone: "warning" },
    approved: { label: "معتمدة", tone: "success" },
    rejected: { label: "مرفوضة", tone: "danger" },
    paid: { label: "مدفوعة", tone: "success" },
    cancelled: { label: "ملغاة", tone: "neutral" },
  },
  bonus_type: {
    one_time: { label: "مكافأة لمرة واحدة", tone: "neutral" },
    performance: { label: "مكافأة أداء", tone: "neutral" },
    sales: { label: "مكافأة مبيعات", tone: "neutral" },
    annual: { label: "مكافأة سنوية", tone: "neutral" },
    custom: { label: "مكافأة مخصصة", tone: "neutral" },
  },
  loan_status: {
    pending: { label: "بانتظار الاعتماد", tone: "warning" },
    approved: { label: "معتمد — بانتظار الصرف", tone: "info" },
    rejected: { label: "مرفوض", tone: "danger" },
    active: { label: "جارٍ السداد", tone: "accent" },
    settled: { label: "مسدد", tone: "success" },
    cancelled: { label: "ملغي", tone: "neutral" },
  },
  loan_type: {
    advance: { label: "سلفة راتب", tone: "neutral" },
    loan: { label: "قرض موظف", tone: "neutral" },
  },
  installment_status: {
    scheduled: { label: "مجدول", tone: "neutral" },
    deducted: { label: "خُصم من الراتب", tone: "success" },
    paid_manually: { label: "سُدد يدوياً", tone: "success" },
    waived: { label: "معفى", tone: "accent" },
    skipped: { label: "مؤجل", tone: "warning" },
  },
  reimbursement_status: {
    not_applicable: { label: "لا ينطبق", tone: "neutral" },
    pending: { label: "بانتظار الاسترداد", tone: "warning" },
    reimbursed: { label: "تم الاسترداد", tone: "success" },
  },
  hr_request_status: {
    pending: { label: "بانتظار الموافقة", tone: "warning" },
    approved: { label: "موافق عليه", tone: "info" },
    rejected: { label: "مرفوض", tone: "danger" },
    in_progress: { label: "قيد التنفيذ", tone: "info" },
    completed: { label: "مكتمل", tone: "success" },
    cancelled: { label: "ملغي", tone: "neutral" },
  },
  application_status: {
    new: { label: "جديد", tone: "info" },
    in_review: { label: "قيد المراجعة", tone: "neutral" },
    contacted: { label: "تم التواصل", tone: "neutral" },
    interview: { label: "مقابلة", tone: "accent" },
    evaluation: { label: "تقييم", tone: "accent" },
    accepted: { label: "مقبول (جاهز للعرض)", tone: "success" },
    offer: { label: "عرض عمل", tone: "warning" },
    offer_accepted: { label: "قبل العرض", tone: "success" },
    hired: { label: "تم التعيين", tone: "success" },
    rejected: { label: "مرفوض", tone: "danger" },
    withdrawn: { label: "انسحب", tone: "neutral" },
  },
  job_status: {
    draft: { label: "مسودة", tone: "neutral" },
    open: { label: "مفتوحة", tone: "success" },
    on_hold: { label: "معلّقة", tone: "warning" },
    closed: { label: "مغلقة", tone: "neutral" },
    filled: { label: "تم شغلها", tone: "info" },
  },
  candidate_status: {
    active: { label: "نشط", tone: "info" },
    hired: { label: "تم تعيينه", tone: "success" },
    archived: { label: "مؤرشف", tone: "neutral" },
    blacklisted: { label: "محظور", tone: "danger" },
  },
  offer_status: {
    draft: { label: "مسودة", tone: "neutral" },
    sent: { label: "مُرسل", tone: "info" },
    accepted: { label: "مقبول", tone: "success" },
    rejected: { label: "مرفوض", tone: "danger" },
    expired: { label: "منتهي", tone: "warning" },
    withdrawn: { label: "مسحوب", tone: "neutral" },
  },
  interview_status: {
    scheduled: { label: "مجدولة", tone: "info" },
    completed: { label: "تمت", tone: "success" },
    cancelled: { label: "ملغاة", tone: "neutral" },
    no_show: { label: "لم يحضر", tone: "warning" },
  },
  interview_outcome: {
    pending: { label: "بانتظار النتيجة", tone: "neutral" },
    passed: { label: "اجتاز", tone: "success" },
    failed: { label: "لم يجتز", tone: "danger" },
  },
  recommendation: {
    strong_yes: { label: "أوصي بشدة", tone: "success" },
    yes: { label: "أوصي", tone: "success" },
    no: { label: "لا أوصي", tone: "warning" },
    strong_no: { label: "لا أوصي إطلاقاً", tone: "danger" },
  },
  goal_status: {
    not_started: { label: "لم يبدأ", tone: "neutral" },
    on_track: { label: "على المسار", tone: "success" },
    at_risk: { label: "معرض للخطر", tone: "warning" },
    off_track: { label: "خارج المسار", tone: "danger" },
    completed: { label: "مكتمل", tone: "success" },
    cancelled: { label: "ملغي", tone: "neutral" },
  },
  cycle_status: {
    draft: { label: "مسودة", tone: "neutral" },
    active: { label: "نشطة", tone: "success" },
    closed: { label: "مغلقة", tone: "neutral" },
  },
  feedback_status: {
    requested: { label: "مطلوب", tone: "warning" },
    submitted: { label: "مُرسل", tone: "success" },
    declined: { label: "معتذر", tone: "neutral" },
  },
  feedback_relationship: {
    manager: { label: "المدير", tone: "neutral" },
    peer: { label: "زميل", tone: "neutral" },
    direct_report: { label: "مرؤوس", tone: "neutral" },
    self: { label: "تقييم ذاتي", tone: "neutral" },
    other: { label: "آخر", tone: "neutral" },
  },
  review_recommendation: {
    none: { label: "لا يوجد", tone: "neutral" },
    promotion: { label: "ترقية", tone: "success" },
    salary_increase: { label: "زيادة راتب", tone: "success" },
    bonus: { label: "مكافأة", tone: "success" },
    pip: { label: "خطة تحسين أداء", tone: "warning" },
    confirm_probation: { label: "تثبيت بعد الاختبار", tone: "success" },
    extend_probation: { label: "تمديد الاختبار", tone: "warning" },
    termination: { label: "إنهاء الخدمة", tone: "danger" },
  },
  schedule_type: {
    fixed: { label: "ثابت", tone: "neutral" },
    shift: { label: "ورديات", tone: "info" },
    night: { label: "وردية ليلية", tone: "accent" },
    flexible: { label: "مرن", tone: "success" },
    remote: { label: "عن بُعد", tone: "success" },
  },
  separation_type: {
    resignation: { label: "استقالة", tone: "neutral" },
    termination: { label: "إنهاء خدمة", tone: "danger" },
    end_of_contract: { label: "انتهاء العقد", tone: "neutral" },
    retirement: { label: "تقاعد", tone: "neutral" },
    mutual: { label: "اتفاق متبادل", tone: "neutral" },
    other: { label: "أخرى", tone: "neutral" },
  },
  checklist_item_status: {
    pending: { label: "لم يبدأ", tone: "neutral" },
    in_progress: { label: "قيد التنفيذ", tone: "info" },
    done: { label: "تم", tone: "success" },
    skipped: { label: "لا ينطبق", tone: "neutral" },
    blocked: { label: "متوقف", tone: "warning" },
  },
  overtime_day_type: {
    workday: { label: "يوم عمل", tone: "neutral" },
    day_off: { label: "يوم راحة", tone: "accent" },
    holiday: { label: "عطلة رسمية", tone: "accent" },
  },
  compensation_change: {
    initial: { label: "راتب مبدئي", tone: "neutral" },
    adjustment: { label: "تعديل راتب", tone: "info" },
    promotion: { label: "ترقية", tone: "success" },
    correction: { label: "تصحيح", tone: "neutral" },
  },
  job_change_type: {
    hire: { label: "تعيين", tone: "success" },
    promotion: { label: "ترقية", tone: "success" },
    transfer: { label: "نقل", tone: "info" },
    title_change: { label: "تغيير المسمى", tone: "neutral" },
    salary_adjustment: { label: "تعديل راتب", tone: "info" },
    demotion: { label: "تخفيض", tone: "warning" },
    status_change: { label: "تغيير الحالة", tone: "neutral" },
  },
};

export function statusDef(map: keyof typeof statusMaps | string, value: string | null | undefined): StatusDef {
  if (!value) return { label: "—", tone: "neutral" };
  return statusMaps[map]?.[value] ?? { label: value.replace(/_/g, " "), tone: "neutral" };
}

export function statusLabel(map: string, value: string | null | undefined): string {
  return statusDef(map, value).label;
}

export function statusOptions(map: string): { value: string; label: string }[] {
  return Object.entries(statusMaps[map] ?? {}).map(([value, def]) => ({ value, label: def.label }));
}

export const eventLabels: Record<string, string> = {
  "lead.created": "إنشاء العميل المحتمل",
  "lead.assigned": "تعيين مسؤول",
  "lead.contacted": "تم التواصل",
  "lead.replied": "رد العميل",
  "lead.qualified": "تأهيل",
  "lead.stage_changed": "تغيير المرحلة",
  "lead.converted": "تحويل إلى صفقة",
  "lead.lost": "خسارة",
  "deal.created": "إنشاء صفقة",
  "deal.updated": "تحديث صفقة",
  "deal.stage_changed": "تغيير مرحلة الصفقة",
  "deal.proposal_sent": "إرسال المقترح",
  "deal.won": "كسب الصفقة",
  "deal.lost": "خسارة الصفقة",
  "payment.created": "تسجيل دفعة",
  "payment.completed": "استلام دفعة",
  "payment.failed": "فشل دفعة",
  "project.created": "إنشاء مشروع",
  "project.status_changed": "تغيير حالة المشروع",
  "project.delayed": "تأخر المشروع",
  "project.completed": "اكتمال المشروع",
  "task.created": "إنشاء مهمة",
  "task.completed": "اكتمال مهمة",
  "task.overdue": "تأخر مهمة",
  "attendance.clock_in": "بدء العمل",
  "attendance.clock_out": "إنهاء العمل",
  "attendance.correction_requested": "طلب تصحيح حضور",
  "attendance.correction_approved": "اعتماد تصحيح حضور",
  // HR & Workforce (docs/bos/28)
  "employee.created": "إنشاء ملف موظف",
  "employee.lifecycle_changed": "تغيير حالة الموظف",
  "employee.promoted": "ترقية",
  "employee.probation_ending": "قرب انتهاء فترة الاختبار",
  "compensation.changed": "تحديث الراتب",
  "overtime.requested": "طلب عمل إضافي",
  "overtime.decided": "قرار العمل الإضافي",
  "leave.requested": "طلب إجازة",
  "leave.approved": "اعتماد إجازة",
  "leave.rejected": "رفض إجازة",
  "loan.decided": "قرار سلفة / قرض",
  "bonus.decided": "قرار مكافأة",
  "hr_request.decided": "قرار طلب موارد بشرية",
  "hr_request.completed": "اكتمال طلب موارد بشرية",
  "employee_expense.decided": "قرار مصروف موظف",
  "employee_expense.approved": "اعتماد مصروف موظف",
  "employee_expense.reimbursed": "استرداد مصروف",
  "employee_document.uploaded": "رفع مستند",
  "employee_document.expiring": "مستند قارب على الانتهاء",
  "employee_document.rejected": "رفض مستند",
  "employee_contract.expiring": "عقد قارب على الانتهاء",
  "onboarding.started": "بدء التهيئة",
  "onboarding.completed": "اكتمال التهيئة",
  "onboarding.task_assigned": "تعيين مهمة تهيئة",
  "offboarding.started": "بدء إنهاء الخدمة",
  "offboarding.completed": "اكتمال إنهاء الخدمة",
  "offboarding.task_assigned": "تعيين مهمة إنهاء خدمة",
  "payroll.approved": "اعتماد الرواتب",
  "payroll.paid": "صرف الرواتب",
  "payslip.published": "نشر قسيمة الراتب",
  "interview.scheduled": "جدولة مقابلة",
  "candidate.stage_changed": "تغيير مرحلة المرشح",
  "candidate.hired": "تعيين مرشح",
  "job_offer.accepted": "قبول عرض العمل",
  "job_offer.rejected": "رفض عرض العمل",
  "performance.goal_assigned": "هدف جديد",
  "performance.feedback_requested": "طلب تقييم 360",
  "review.submitted": "إرسال مراجعة أداء",
};
