// Canonical URLs for every BOS entity type (timeline, notifications, search).

const routes: Record<string, (id: string) => string> = {
  lead: (id) => `/admin/sales/leads/${id}`,
  deal: (id) => `/admin/sales/deals/${id}`,
  proposal: (id) => `/admin/sales/proposals/${id}`,
  contract: (id) => `/admin/sales/contracts/${id}`,
  activity: () => `/admin/sales/activities`,
  meeting: (id) => `/admin/communication/meetings/${id}`,
  client: (id) => `/admin/clients/${id}`,
  contact: (id) => `/admin/contacts/${id}`,
  invoice: (id) => `/admin/finance/invoices/${id}`,
  payment: (id) => `/admin/finance/payments/${id}`,
  commission: () => `/admin/finance/commissions`,
  expense: (id) => `/admin/finance/expenses/${id}`,
  vendor: (id) => `/admin/finance/vendors/${id}`,
  employee: (id) => `/admin/team/employees/${id}`,
  document: (id) => `/admin/documents/${id}`,
  conversation: (id) => `/admin/support/inbox?c=${id}`,
  support_customer: (id) => `/admin/support/customers/${id}`,
  document_template: (id) => `/admin/documents/templates/${id}`,
  attendance_record: () => `/admin/team/attendance`,
  attendance_correction: () => `/admin/team/attendance/corrections`,
  leave_request: () => `/admin/team/leave`,
  overtime_request: () => `/admin/team/overtime`,
  approval: () => `/admin/approvals`,
  ticket: (id) => `/admin/support/tickets/${id}`,
  kb_article: (id) => `/admin/knowledge/articles/${id}`,
  file: (id) => `/api/bos/files/${id}`,
  channel: (id) => `/admin/communication/chat/${id}`,
  device: (id) => `/admin/team/devices/${id}`,
  // HR & Workforce (docs/bos/28)
  payroll_run: (id) => `/admin/team/payroll/runs/${id}`,
  payslip: (id) => `/admin/team/payroll/payslips/${id}`,
  employee_document: () => `/admin/team/documents`,
  employee_contract: (id) => `/admin/team/documents/contracts/${id}`,
  candidate: (id) => `/admin/team/recruitment/candidates/${id}`,
  career_job: (id) => `/admin/team/recruitment/jobs/${id}`,
  career_application: (id) => `/admin/team/recruitment/applications/${id}`,
  job_offer: () => `/admin/team/recruitment/offers`,
  hr_request: () => `/admin/team/requests/other`,
  employee_loan: () => `/admin/team/payroll/loans`,
  employee_bonus: () => `/admin/team/payroll/bonuses`,
  employee_expense: (id) => `/admin/team/requests/expenses?open=${id}`,
  performance_goal: () => `/admin/team/performance/goals`,
  performance_review: () => `/admin/team/performance/reviews`,
  review_cycle: () => `/admin/team/performance/reviews`,
  performance_feedback: () => `/admin/team/performance/feedback`,
  work_schedule: () => `/admin/team/schedules/list`,
  holiday: () => `/admin/team/schedules/holidays`,
};

export function entityHref(entityType: string | null | undefined, entityId: string | null | undefined): string | null {
  if (!entityType || !entityId) return null;
  const route = routes[entityType];
  return route ? route(entityId) : null;
}

export const entityTypeLabels: Record<string, string> = {
  document: "مستند",
  conversation: "محادثة دعم",
  lead: "عميل محتمل",
  deal: "صفقة",
  proposal: "مقترح",
  contract: "عقد",
  activity: "نشاط",
  meeting: "اجتماع",
  client: "حساب",
  contact: "جهة اتصال",
  invoice: "فاتورة",
  payment: "دفعة",
  commission: "عمولة",
  expense: "مصروف",
  vendor: "مورد",
  employee: "موظف",
  approval: "موافقة",
  ticket: "تذكرة",
  kb_article: "مقال معرفي",
  file: "ملف",
  channel: "قناة",
  device: "جهاز",
  payroll_run: "دورة رواتب",
  payslip: "قسيمة راتب",
  employee_document: "مستند موظف",
  employee_contract: "عقد موظف",
  candidate: "مرشح",
  career_job: "وظيفة",
  career_application: "طلب توظيف",
  job_offer: "عرض عمل",
  hr_request: "طلب موارد بشرية",
  employee_loan: "سلفة / قرض",
  employee_bonus: "مكافأة",
  employee_expense: "مصروف موظف",
  performance_goal: "هدف",
  performance_review: "مراجعة أداء",
};
