import type { Doc, Localized } from "./types";

// Legal pages. They describe how Yolias actually works today (magic-link
// sign-in, workspace isolation, AI processing, the cookies the app sets).
// Have them reviewed by counsel before accepting live payments.

export const LEGAL_UPDATED = "2026-10-07";
export const legalSlugs = ["privacy", "terms", "refunds", "cookies", "security"] as const;
export type LegalSlug = (typeof legalSlugs)[number];

export const legal: Record<LegalSlug, Localized<Doc>> = {
  privacy: {
    en: {
      title: "Privacy Policy",
      summary: "What Yolias collects, why, who processes it with us, and the choices you have.",
      blocks: [
        { h2: "Who we are" },
        { p: "Yolias is a customer-discovery product made by Taysonsta (“we”, “us”). This policy covers the Yolias website and app. For questions or requests, use the [Contact page](/contact)." },
        { h2: "Information we collect" },
        { h3: "Account and workspace" },
        { ul: [
          "Your email address, name and optional profile picture.",
          "Your company profile, entered during onboarding: company name, website, industry, products and services, ideal customer profile and target markets.",
          "Preferences such as language, theme, text size, time zone, country and notification settings.",
          "Team membership, roles and invitations you send.",
        ] },
        { h3: "What you create in Yolias" },
        { ul: [
          "Searches you run, and the customer profile Yolias derives from them.",
          "Campaigns, their criteria and activity, and the companies and prospects they produce.",
          "Files you attach to a search are read to understand your request. We keep only their name and type, not their contents.",
          "Conversations with Yolias AI, and facts you ask it to remember about your business.",
          "Email and LinkedIn messages Yolias writes for you, your edits, and where and when you opened them (Gmail, Outlook, your email app or LinkedIn). Yolias doesn’t send them; you do, from your own account.",
        ] },
        { h3: "Payments" },
        { p: "Card payments are made on our payment provider’s page (Paymob). We receive the payment result, amount and a reference — never your card number or security code." },
        { h3: "Business contact data about prospects" },
        { p: "Campaigns collect professional information about companies and their decision makers — such as name, job title, company, location and business contact channels — from the data sources Yolias connects to. Each record keeps the source it came from." },
        { h3: "Technical and usage data" },
        { p: "Sign-in events, IP address and browser information used to keep sessions secure, plus counts of discovery usage used for plan limits. We also record product events (for example: a search started, a campaign delivered results, a payment succeeded) linked to your user id — not your email — and error reports with personal details removed." },
        { h3: "Messages you send us" },
        { p: "What you submit through the Contact form, including your name, email, company and message." },
        { h2: "How we use information" },
        { ul: [
          "To provide the service: sign you in, run your searches and campaigns, and show your results.",
          "To apply plan limits, prevent abuse and keep accounts secure.",
          "To answer messages and support requests.",
          "To improve Yolias using aggregated usage, never by selling your data.",
        ] },
        { h2: "AI processing" },
        { p: "When you start a search, chat with Yolias AI or ask it to personalize a message, the relevant text, attachments, your company profile and the needed prospect details are sent to our AI providers to produce the answer. They process this data on our behalf under their commercial terms for business customers." },
        { h2: "Who processes data with us" },
        { table: { head: ["Provider role", "Purpose"], rows: [
          ["Database, authentication and file storage", "Hosting your workspace data, sign-in links and profile pictures"],
          ["AI model providers", "Understanding searches, Yolias AI chat and message drafts"],
          ["Business data providers", "Finding companies, decision makers and their business contact details"],
          ["Email delivery", "Sending sign-in links, invitations, receipts and alerts"],
          ["Hosting", "Serving the website and app"],
          ["Payment provider (Paymob)", "Processing card payments"],
          ["Product analytics (PostHog)", "Understanding how Yolias is used, to improve it"],
          ["Error monitoring (Sentry)", "Finding and fixing errors"],
          ["Session analytics (Microsoft Clarity), with your consent", "Seeing where pages are hard to use"],
          ["Advertising measurement (Meta), with your consent", "Measuring our own ads: page views, checkout started and purchases"],
        ] } },
        { p: "We do not sell personal information. Meta receives only the events listed above, and only if you accept cookies; it never receives your workspace data or prospect data." },
        { h2: "Retention and deletion" },
        { p: "We keep account and workspace data while your account is active. When you delete your account from Settings → Account, your profile is removed, and when you are the only member of your workspace, its searches, campaigns, companies and prospects are deleted with it. Contact messages are kept only as long as needed to handle them." },
        { h2: "Your rights" },
        { p: "Depending on where you live, you can ask to access, correct, export or delete your personal data, or object to certain processing. People whose business details appear in a Yolias campaign can make the same requests. Send them through the [Contact page](/contact) and we will respond within the time the law requires." },
        { h2: "Cookies" },
        { p: "Yolias uses essential and preference cookies. Analytics and advertising cookies are used only if you accept them in the cookie banner. The [Cookie Policy](/legal/cookies) lists each one." },
        { h2: "Changes" },
        { p: "If we change this policy in a meaningful way, we will update the date above and tell signed-in users in the app or by email." },
      ],
    },
    ar: {
      title: "سياسة الخصوصية",
      summary: "ما الذي يجمعه يولـياس، ولماذا، ومن يعالج البيانات معنا، والخيارات المتاحة لك.",
      blocks: [
        { h2: "من نحن" },
        { p: "يولـياس منتج لاكتشاف العملاء تقدمه Taysonsta («نحن»). تشمل هذه السياسة موقع يولـياس وتطبيقه. للأسئلة أو الطلبات استخدم [صفحة التواصل](/contact)." },
        { h2: "المعلومات التي نجمعها" },
        { h3: "الحساب ومساحة العمل" },
        { ul: [
          "بريدك الإلكتروني واسمك وصورتك الشخصية الاختيارية.",
          "ملف شركتك كما أدخلته أثناء الإعداد الأولي: اسم الشركة وموقعها ومجالها ومنتجاتها وخدماتها والعميل المثالي والأسواق المستهدفة.",
          "تفضيلاتك مثل اللغة والمظهر وحجم النص والمنطقة الزمنية والدولة والإشعارات.",
          "عضوية الفريق والأدوار والدعوات التي ترسلها.",
        ] },
        { h3: "ما تنشئه داخل يولـياس" },
        { ul: [
          "عمليات البحث التي تجريها، وملف العميل المثالي الذي يستخرجه يولـياس منها.",
          "الحملات ومعاييرها ونشاطها، والشركات والعملاء المحتملون الناتجون عنها.",
          "الملفات التي ترفقها بالبحث تُقرأ لفهم طلبك فقط، ونحتفظ باسمها ونوعها دون محتواها.",
          "محادثاتك مع Yolias AI، والمعلومات التي تطلب منه تذكّرها عن عملك.",
          "رسائل الإيميل ولينكدإن التي يكتبها يولـياس لك، وتعديلاتك عليها، وأين ومتى فتحتها (Gmail أو Outlook أو تطبيق البريد أو لينكدإن). يولـياس لا يرسلها، بل ترسلها أنت من حسابك.",
        ] },
        { h3: "المدفوعات" },
        { p: "يتم الدفع بالبطاقة في صفحة مزوّد الدفع (Paymob). نستلم نتيجة الدفع والمبلغ ومرجعًا للعملية فقط، ولا نستلم رقم بطاقتك أو رمز الأمان أبدًا." },
        { h3: "بيانات التواصل المهنية للعملاء المحتملين" },
        { p: "تجمع الحملات معلومات مهنية عن الشركات وصنّاع القرار فيها — مثل الاسم والمسمى الوظيفي والشركة والموقع وقنوات التواصل المهنية — من مصادر البيانات التي يتصل بها يولـياس. ويحتفظ كل سجل بالمصدر الذي جاء منه." },
        { h3: "البيانات التقنية وبيانات الاستخدام" },
        { p: "أحداث تسجيل الدخول وعنوان IP ومعلومات المتصفح لتأمين الجلسات، إضافةً إلى أعداد الاستخدام لتطبيق حدود الخطط. ونسجّل كذلك أحداث استخدام المنتج (مثل: بدء بحث، أو تسليم حملة لنتائج، أو نجاح دفعة) مرتبطة بمعرّف المستخدم وليس ببريدك، وتقارير الأخطاء بعد حذف البيانات الشخصية منها." },
        { h3: "الرسائل التي ترسلها لنا" },
        { p: "ما ترسله عبر نموذج التواصل، بما في ذلك اسمك وبريدك وشركتك ورسالتك." },
        { h2: "كيف نستخدم المعلومات" },
        { ul: [
          "لتقديم الخدمة: تسجيل دخولك، وتشغيل عمليات البحث والحملات، وعرض نتائجك.",
          "لتطبيق حدود الخطط ومنع إساءة الاستخدام وتأمين الحسابات.",
          "للرد على الرسائل وطلبات الدعم.",
          "لتحسين يولـياس باستخدام بيانات استخدام مجمّعة، دون بيع بياناتك أبدًا.",
        ] },
        { h2: "المعالجة بالذكاء الاصطناعي" },
        { p: "عند بدء بحث أو التحدث مع Yolias AI أو طلب تخصيص رسالة، يُرسل النص المطلوب والمرفقات وملف شركتك وبيانات العميل المحتمل اللازمة إلى مزودي الذكاء الاصطناعي لإنتاج الإجابة. يعالجون هذه البيانات نيابةً عنا وفق شروطهم التجارية لعملاء الأعمال." },
        { h2: "من يعالج البيانات معنا" },
        { table: { head: ["دور المزود", "الغرض"], rows: [
          ["قاعدة البيانات والمصادقة وتخزين الملفات", "استضافة بيانات مساحة العمل وروابط الدخول والصور الشخصية"],
          ["مزودو نماذج الذكاء الاصطناعي", "فهم عمليات البحث ومحادثة Yolias AI وكتابة مسودات الرسائل"],
          ["مزودو بيانات الشركات", "إيجاد الشركات وصنّاع القرار وبيانات التواصل المهنية"],
          ["إرسال البريد الإلكتروني", "إرسال روابط الدخول والدعوات والإيصالات والتنبيهات"],
          ["الاستضافة", "تشغيل الموقع والتطبيق"],
          ["مزود الدفع (Paymob)", "معالجة المدفوعات بالبطاقة"],
          ["تحليلات المنتج (PostHog)", "فهم طريقة استخدام يولـياس لتحسينه"],
          ["مراقبة الأخطاء (Sentry)", "اكتشاف الأخطاء وإصلاحها"],
          ["تحليل الجلسات (Microsoft Clarity) بموافقتك", "معرفة الأماكن الصعبة الاستخدام في الصفحات"],
          ["قياس الإعلانات (Meta) بموافقتك", "قياس إعلاناتنا: زيارات الصفحات وبدء الدفع وعمليات الشراء"],
        ] } },
        { p: "لا نبيع المعلومات الشخصية. وتستلم Meta الأحداث المذكورة أعلاه فقط، وفقط إذا قبلت ملفات تعريف الارتباط، ولا تستلم بيانات مساحة عملك أو بيانات العملاء المحتملين أبدًا." },
        { h2: "الاحتفاظ والحذف" },
        { p: "نحتفظ ببيانات الحساب ومساحة العمل ما دام حسابك نشطًا. عند حذف حسابك من الإعدادات ← الحساب يُحذف ملفك الشخصي، وإذا كنت العضو الوحيد في مساحة العمل تُحذف معها عمليات البحث والحملات والشركات والعملاء المحتملون. ونحتفظ برسائل التواصل فقط بالقدر اللازم لمعالجتها." },
        { h2: "حقوقك" },
        { p: "بحسب مكان إقامتك، يمكنك طلب الوصول إلى بياناتك الشخصية أو تصحيحها أو تصديرها أو حذفها، أو الاعتراض على بعض أوجه المعالجة. ويحق للأشخاص الذين تظهر بياناتهم المهنية في حملات يولـياس تقديم الطلبات نفسها. أرسلها عبر [صفحة التواصل](/contact) وسنرد خلال المدة التي يحددها القانون." },
        { h2: "ملفات تعريف الارتباط" },
        { p: "يستخدم يولـياس ملفات تعريف الارتباط الأساسية وملفات التفضيلات. أما ملفات التحليلات والإعلانات فلا تُستخدم إلا إذا قبلتها في شريط ملفات تعريف الارتباط. تجد كل ملف في [سياسة ملفات تعريف الارتباط](/legal/cookies)." },
        { h2: "التغييرات" },
        { p: "إذا غيّرنا هذه السياسة تغييرًا جوهريًا، سنحدّث التاريخ أعلاه ونبلغ المستخدمين المسجّلين داخل التطبيق أو عبر البريد." },
      ],
    },
  },
  terms: {
    en: {
      title: "Terms of Service",
      summary: "The agreement between you and Taysonsta for using Yolias.",
      blocks: [
        { h2: "Agreement" },
        { p: "By creating an account or using Yolias you agree to these terms on behalf of yourself and the organization you represent. Yolias is intended for business use." },
        { h2: "Your account" },
        { ul: [
          "You sign in with a link sent to your email or with Google; keep access to them secure. You can add two-factor authentication.",
          "The workspace owner and admins control who joins the workspace and which plan it uses.",
          "You are responsible for activity in your workspace.",
        ] },
        { h2: "Plans and billing" },
        { ul: [
          "Plans differ by monthly usage limits; every plan includes unlimited users.",
          "You can pay monthly or annually. The annual price is twelve times the monthly price and is charged upfront.",
          "At the end of each period we issue a renewal invoice; the plan continues once it’s paid. Nothing is charged automatically. Prices exclude applicable taxes.",
          "Each plan includes a number of results (prospects) per month. A result is counted when it is delivered to you, even if no verified email was found. A company or place counts once; finding its decision makers afterwards is included.",
          "Usage beyond your plan’s limits is not available until the next period, an upgrade or a purchase of extra prospects. Extra prospects don’t expire.",
          "Prices are in US dollars. Card payments are processed by our payment provider and charged in Egyptian pounds at the day’s exchange rate.",
          "Refunds follow the [Refund Policy](/legal/refunds).",
        ] },
        { h2: "Acceptable use" },
        { p: "You will not use Yolias to:" },
        { ul: [
          "send unsolicited bulk messages or contact people in ways that break anti-spam or data protection laws;",
          "collect data about individuals for purposes unrelated to legitimate business outreach;",
          "resell or publish prospect data as a standalone database;",
          "probe, overload or work around the security or limits of the service.",
        ] },
        { h2: "Prospect data and your obligations" },
        { p: "Yolias helps you discover businesses and professional contacts. How you use that information is your decision and your responsibility: you must have a lawful basis to contact people, honor opt-out requests, and follow the laws that apply to you and to them, such as personal data protection laws in Saudi Arabia, the UAE and the EU." },
        { h2: "Messages you send" },
        { p: "Yolias can write an email or a LinkedIn message for a prospect. You edit it and send it yourself from your own email or LinkedIn account; Yolias doesn’t send messages. You are responsible for their content and recipients, and for following the rules of your email provider and of LinkedIn." },
        { h2: "AI output" },
        { p: "Customer profiles, match scores, enriched data and message drafts are produced automatically and can be incomplete or wrong. Review results before relying on them." },
        { h2: "Your content" },
        { p: "You own the searches, files and data you put into Yolias and the results you export. You give us permission to process them only to provide and secure the service." },
        { h2: "Our service" },
        { p: "Yolias, its software and brand belong to Taysonsta. We improve the product continuously and may change or retire features; when a change materially reduces what your plan includes, we will tell you in advance." },
        { h2: "Suspension and termination" },
        { p: "You can stop using Yolias and delete your account at any time. We may suspend or close accounts that break these terms or put other users at risk, and will tell you why where the law allows." },
        { h2: "Disclaimers and liability" },
        { p: "Yolias is provided “as is”. To the extent the law allows, we are not liable for indirect or consequential losses, and our total liability for any claim is limited to the fees you paid for Yolias in the twelve months before the claim." },
        { h2: "Changes to these terms" },
        { p: "We will post updated terms here with a new date and notify signed-in users of material changes. Continuing to use Yolias after that means you accept them." },
        { h2: "Contact" },
        { p: "Questions about these terms: [Contact page](/contact)." },
      ],
    },
    ar: {
      title: "شروط الخدمة",
      summary: "الاتفاق بينك وبين Taysonsta لاستخدام يولـياس.",
      blocks: [
        { h2: "الاتفاق" },
        { p: "بإنشاء حساب أو استخدام يولـياس فإنك توافق على هذه الشروط عن نفسك وعن الجهة التي تمثلها. يولـياس مخصص للاستخدام التجاري." },
        { h2: "حسابك" },
        { ul: [
          "تسجّل الدخول برابط يُرسل إلى بريدك أو بحساب Google؛ حافظ على أمان الوصول إليهما. ويمكنك تفعيل المصادقة الثنائية.",
          "يتحكم مالك مساحة العمل ومسؤولوها في من ينضم إليها وفي الخطة المستخدمة.",
          "أنت مسؤول عن النشاط الذي يتم داخل مساحة عملك.",
        ] },
        { h2: "الخطط والفوترة" },
        { ul: [
          "تختلف الخطط في حدود الاستخدام الشهرية، وتشمل كل خطة مستخدمين غير محدودين.",
          "يمكنك الدفع شهريًا أو سنويًا. السعر السنوي يساوي اثني عشر ضعف السعر الشهري ويُدفع مقدمًا.",
          "في نهاية كل فترة نُصدر فاتورة تجديد، وتستمر الخطة بعد دفعها. لا يُخصم أي مبلغ تلقائيًا. الأسعار لا تشمل الضرائب المطبقة.",
          "تتضمن كل خطة عددًا من النتائج (العملاء المحتملين) شهريًا. تُحتسب النتيجة عند تسليمها إليك حتى لو لم يُعثر على بريد موثّق. والشركة أو النشاط يُحتسب مرة واحدة، وإيجاد صنّاع القرار فيه لاحقًا مشمول.",
          "لا يتوفر استخدام يتجاوز حدود خطتك حتى الفترة التالية أو الترقية أو شراء عملاء محتملين إضافيين. العملاء المحتملون الإضافيون لا تنتهي صلاحيتهم.",
          "الأسعار بالدولار الأمريكي. تُعالج المدفوعات بالبطاقة عبر مزوّد الدفع وتُخصم بالجنيه المصري بسعر صرف اليوم.",
          "تخضع المبالغ المستردة لـ[سياسة الاسترداد](/legal/refunds).",
        ] },
        { h2: "الاستخدام المقبول" },
        { p: "لن تستخدم يولـياس من أجل:" },
        { ul: [
          "إرسال رسائل جماعية غير مرغوب فيها أو التواصل مع الأشخاص بطرق تخالف قوانين مكافحة الرسائل المزعجة أو حماية البيانات؛",
          "جمع بيانات عن الأفراد لأغراض لا تتعلق بالتواصل التجاري المشروع؛",
          "إعادة بيع بيانات العملاء المحتملين أو نشرها كقاعدة بيانات مستقلة؛",
          "اختبار أمان الخدمة أو إثقالها أو التحايل على حدودها.",
        ] },
        { h2: "بيانات العملاء المحتملين والتزاماتك" },
        { p: "يساعدك يولـياس على اكتشاف الشركات وجهات الاتصال المهنية. أما طريقة استخدامك لهذه المعلومات فقرارك ومسؤوليتك: يجب أن يكون لديك أساس قانوني للتواصل، وأن تحترم طلبات إلغاء الاشتراك، وأن تلتزم بالقوانين المطبقة عليك وعليهم، مثل قوانين حماية البيانات الشخصية في السعودية والإمارات والاتحاد الأوروبي." },
        { h2: "الرسائل التي ترسلها" },
        { p: "يمكن ليولـياس كتابة رسالة إيميل أو لينكدإن لعميل محتمل. تعدّلها وترسلها أنت من بريدك أو حسابك على لينكدإن؛ يولـياس لا يرسل الرسائل. وأنت مسؤول عن محتواها ومستلميها، وعن الالتزام بقواعد مزود بريدك ولينكدإن." },
        { h2: "مخرجات الذكاء الاصطناعي" },
        { p: "ملفات العملاء ونسب التطابق والبيانات المُثراة ومسودات الرسائل تُنتج تلقائيًا وقد تكون ناقصة أو غير دقيقة. راجع النتائج قبل الاعتماد عليها." },
        { h2: "محتواك" },
        { p: "تملك عمليات البحث والملفات والبيانات التي تضعها في يولـياس والنتائج التي تصدّرها. وتمنحنا الإذن بمعالجتها فقط لتقديم الخدمة وتأمينها." },
        { h2: "خدمتنا" },
        { p: "يولـياس وبرمجياته وعلامته التجارية ملك لـ Taysonsta. نطوّر المنتج باستمرار وقد نغيّر بعض الميزات أو نوقفها؛ وإذا قلّل تغيير ما بشكل جوهري مما تشمله خطتك فسنبلغك مسبقًا." },
        { h2: "الإيقاف والإنهاء" },
        { p: "يمكنك التوقف عن استخدام يولـياس وحذف حسابك في أي وقت. وقد نوقف أو نغلق الحسابات التي تخالف هذه الشروط أو تعرّض المستخدمين الآخرين للخطر، وسنوضح السبب متى سمح القانون بذلك." },
        { h2: "إخلاء المسؤولية وحدودها" },
        { p: "يُقدَّم يولـياس «كما هو». وفي الحدود التي يسمح بها القانون، لا نتحمل مسؤولية الخسائر غير المباشرة أو التبعية، وتقتصر مسؤوليتنا الإجمالية عن أي مطالبة على الرسوم التي دفعتها مقابل يولـياس خلال الاثني عشر شهرًا السابقة للمطالبة." },
        { h2: "تغيير هذه الشروط" },
        { p: "سننشر الشروط المحدّثة هنا بتاريخ جديد ونبلغ المستخدمين المسجّلين بالتغييرات الجوهرية. واستمرارك في استخدام يولـياس بعد ذلك يعني قبولك لها." },
        { h2: "التواصل" },
        { p: "للأسئلة حول هذه الشروط: [صفحة التواصل](/contact)." },
      ],
    },
  },
  refunds: {
    en: {
      title: "Refund Policy",
      summary: "When you can get your money back for a Yolias plan or extra prospects, and how.",
      blocks: [
        { h2: "Summary" },
        { p: "You can cancel any time from Settings → Billing; your plan stays active until the end of the period you paid for. If something went wrong with a payment, or you paid and didn’t use what you bought, ask us within 7 days and we will refund it." },
        { h2: "Subscriptions" },
        { ul: [
          "First payment or renewal: a full refund if you ask within 7 days of the payment and no prospects were delivered in that period.",
          "If prospects were delivered in that period, the payment is not refundable, but you can cancel so the plan doesn’t renew.",
          "Annual plans: within 7 days of the payment under the same condition; after that, the plan stays active until the end of the year.",
          "Renewals are never charged automatically: a renewal is paid only when you pay its invoice.",
        ] },
        { h2: "Extra prospects" },
        { ul: [
          "A pack is refundable within 7 days of the purchase if none of its prospects were used.",
          "Prospects that were used are not refundable. Extra prospects don’t expire, so there is no refund for unused time.",
        ] },
        { h2: "Always refunded" },
        { ul: [
          "Duplicate charges, or a charge for something you didn’t receive because of an error on our side.",
          "A charge made after you canceled, for the period after the cancellation.",
        ] },
        { h2: "How to ask" },
        { p: "Send a request through the [Contact page](/contact?topic=sales) from the workspace’s owner or admin email, with the invoice number. We answer within 3 business days." },
        { h2: "How refunds are paid" },
        { p: "Refunds go back to the card used for the payment through our payment provider, usually within 5–14 business days depending on your bank. Prices are in US dollars and cards are charged in Egyptian pounds at the day’s rate; the refund is the same amount in pounds that was charged, so your bank’s exchange rate may make it differ slightly. A refunded payment’s invoice is voided, and the plan or prospects it paid for are removed." },
        { h2: "Changes" },
        { p: "We may update this policy; the date at the top shows the latest version. Payments made before a change follow the policy in force when they were made." },
      ],
    },
    ar: {
      title: "سياسة الاسترداد",
      summary: "متى يمكنك استرداد ما دفعته مقابل خطة يولـياس أو العملاء المحتملين الإضافيين، وكيف.",
      blocks: [
        { h2: "باختصار" },
        { p: "يمكنك الإلغاء في أي وقت من الإعدادات ← الفوترة، وتبقى خطتك فعّالة حتى نهاية الفترة المدفوعة. إذا حدثت مشكلة في الدفع، أو دفعت ولم تستخدم ما اشتريته، اطلب الاسترداد خلال 7 أيام وسنعيد المبلغ." },
        { h2: "الاشتراكات" },
        { ul: [
          "الدفعة الأولى أو التجديد: استرداد كامل إذا طلبته خلال 7 أيام من الدفع ولم يُسلَّم أي عميل محتمل في تلك الفترة.",
          "إذا سُلِّم عملاء محتملون في تلك الفترة فلا يُسترد المبلغ، ويمكنك الإلغاء حتى لا تتجدد الخطة.",
          "الخطط السنوية: خلال 7 أيام من الدفع بالشرط نفسه، وبعد ذلك تبقى الخطة فعّالة حتى نهاية السنة.",
          "لا يُخصم التجديد تلقائيًا أبدًا: يُدفع التجديد فقط عندما تدفع فاتورته.",
        ] },
        { h2: "العملاء المحتملون الإضافيون" },
        { ul: [
          "تُسترد الباقة خلال 7 أيام من الشراء إذا لم يُستخدم أي عميل محتمل منها.",
          "العملاء المحتملون المستخدمون لا يُستردون. والعملاء الإضافيون لا تنتهي صلاحيتهم، فلا يوجد استرداد مقابل وقت غير مستخدم.",
        ] },
        { h2: "يُسترد دائمًا" },
        { ul: [
          "الخصم المكرر، أو الخصم مقابل شيء لم تحصل عليه بسبب خطأ من جانبنا.",
          "أي خصم تم بعد إلغائك، عن الفترة التي تلي الإلغاء.",
        ] },
        { h2: "كيف تطلب الاسترداد" },
        { p: "أرسل طلبك عبر [صفحة التواصل](/contact?topic=sales) من بريد مالك مساحة العمل أو المسؤول، مع رقم الفاتورة. نرد خلال 3 أيام عمل." },
        { h2: "كيف يُعاد المبلغ" },
        { p: "يُعاد المبلغ إلى البطاقة المستخدمة في الدفع عبر مزوّد الدفع، عادةً خلال 5–14 يوم عمل حسب البنك. الأسعار بالدولار الأمريكي وتُخصم من البطاقة بالجنيه المصري بسعر صرف اليوم؛ ويُعاد المبلغ نفسه الذي خُصم بالجنيه، وقد يختلف قليلاً بسبب سعر صرف البنك. تُلغى فاتورة الدفعة المستردة، وتُزال الخطة أو العملاء المحتملون الذين دُفعت مقابلها." },
        { h2: "التغييرات" },
        { p: "قد نحدّث هذه السياسة، ويوضح التاريخ في أعلى الصفحة آخر إصدار. تخضع المدفوعات السابقة لأي تغيير للسياسة السارية وقت الدفع." },
      ],
    },
  },
  cookies: {
    en: {
      title: "Cookie Policy",
      summary: "The cookies Yolias sets, what each one does and how long it lasts.",
      blocks: [
        { h2: "Our approach" },
        { p: "Yolias always uses the cookies it needs to sign you in and remember a few choices. Analytics and advertising cookies are used only if you choose “Accept all” in the cookie banner; with “Essential only” they are never set. You can change your choice by deleting the yolias_consent cookie." },
        { h2: "Cookies we set" },
        { table: { head: ["Cookie", "Type", "Purpose", "Duration"], rows: [
          ["sb-…-auth-token", "Essential", "Keeps you signed in after you open a magic link", "Until you sign out or the session expires"],
          ["yolias_locale", "Preference", "Remembers Arabic or English", "1 year"],
          ["yolias_plan, yolias_period", "Essential", "Remember the plan and billing period you chose on Pricing until checkout", "30 days, removed after checkout"],
          ["yolias_sidebar", "Preference", "Remembers whether the app sidebar is open", "1 year"],
          ["yolias_consent", "Essential", "Remembers your cookie choice", "1 year"],
          ["ph_…_posthog", "Analytics (with consent)", "PostHog: counts visits and product use without your email", "1 year"],
          ["_clck, _clsk", "Analytics (with consent)", "Microsoft Clarity: shows where pages are hard to use", "Up to 1 year"],
          ["_fbp", "Advertising (with consent)", "Meta Pixel: measures our ads (page views, checkout started, purchases)", "3 months"],
        ] } },
        { p: "Error monitoring (Sentry) sets no cookies." },
        { h2: "Managing cookies" },
        { p: "You can delete cookies in your browser settings at any time. Removing the essential sign-in cookie signs you out; removing preference cookies resets your language and layout choices." },
        { h2: "Changes" },
        { p: "If we add a cookie, it will appear in this table before it is used." },
      ],
    },
    ar: {
      title: "سياسة ملفات تعريف الارتباط",
      summary: "ملفات تعريف الارتباط التي يضعها يولـياس، ووظيفة كل منها، ومدتها.",
      blocks: [
        { h2: "نهجنا" },
        { p: "يستخدم يولـياس دائمًا ملفات تعريف الارتباط اللازمة لتسجيل دخولك وتذكّر بعض اختياراتك. أما ملفات التحليلات والإعلانات فتُستخدم فقط إذا اخترت «قبول الكل» في شريط ملفات تعريف الارتباط، ومع «الأساسية فقط» لا تُستخدم أبدًا. ويمكنك تغيير اختيارك بحذف ملف yolias_consent." },
        { h2: "الملفات التي نستخدمها" },
        { table: { head: ["الملف", "النوع", "الغرض", "المدة"], rows: [
          ["sb-…-auth-token", "أساسي", "يبقيك مسجّل الدخول بعد فتح الرابط السحري", "حتى تسجيل الخروج أو انتهاء الجلسة"],
          ["yolias_locale", "تفضيلات", "يتذكر اختيارك بين العربية والإنجليزية", "سنة واحدة"],
          ["yolias_plan, yolias_period", "أساسي", "يتذكر الخطة وفترة الفوترة التي اخترتها في صفحة الأسعار حتى الاشتراك", "30 يومًا، ويُحذف بعد الاشتراك"],
          ["yolias_sidebar", "تفضيلات", "يتذكر ما إذا كان الشريط الجانبي مفتوحًا", "سنة واحدة"],
          ["yolias_consent", "أساسي", "يتذكر اختيارك لملفات تعريف الارتباط", "سنة واحدة"],
          ["ph_…_posthog", "تحليلات (بموافقتك)", "PostHog: يحسب الزيارات واستخدام المنتج دون بريدك", "سنة واحدة"],
          ["_clck, _clsk", "تحليلات (بموافقتك)", "Microsoft Clarity: يوضح الأماكن الصعبة الاستخدام في الصفحات", "حتى سنة"],
          ["_fbp", "إعلانات (بموافقتك)", "Meta Pixel: يقيس إعلاناتنا (زيارات الصفحات وبدء الدفع وعمليات الشراء)", "3 أشهر"],
        ] } },
        { p: "مراقبة الأخطاء (Sentry) لا تضع أي ملفات تعريف ارتباط." },
        { h2: "إدارة الملفات" },
        { p: "يمكنك حذف ملفات تعريف الارتباط من إعدادات المتصفح في أي وقت. حذف ملف تسجيل الدخول يخرجك من حسابك، وحذف ملفات التفضيلات يعيد إعدادات اللغة والتخطيط." },
        { h2: "التغييرات" },
        { p: "إذا أضفنا ملفًا جديدًا فسيظهر في هذا الجدول قبل استخدامه." },
      ],
    },
  },
  security: {
    en: {
      title: "Security",
      summary: "How Yolias protects your account, your workspace and the data you discover.",
      blocks: [
        { h2: "Sign-in without passwords" },
        { p: "Yolias uses email sign-in links or Google instead of passwords, so there is no password to reuse, phish or leak. Each link works once and expires after one hour. You can add two-factor authentication with an authenticator app, and from Settings → Account sign out of every device at once." },
        { h2: "Workspace isolation" },
        { p: "Every search, campaign, company and prospect belongs to a workspace. Database row-level security rules allow access only to members of that workspace, and they are enforced by the database itself, not only by the app." },
        { h2: "Roles" },
        { ul: [
          "**Owner** — manages the plan and the team.",
          "**Admin** — invites and removes members, manages the plan.",
          "**Member** — works with searches, campaigns and prospects.",
        ] },
        { h2: "Data protection" },
        { ul: [
          "All traffic to Yolias is encrypted in transit with TLS.",
          "Data is stored with our database provider, encrypted at rest.",
          "Privileged keys are used only on the server and never reach the browser.",
          "Files attached to a search are read to understand it and are not stored.",
          "Card details are entered on the payment provider’s page and never reach Yolias.",
          "Errors are monitored to fix them quickly; reports are stripped of personal details and secrets.",
        ] },
        { h2: "AI requests" },
        { p: "Searches are sent to our AI provider only to produce your customer profile. We send the minimum needed: the request, its attachments and your business context." },
        { h2: "Deleting data" },
        { p: "Deleting your account removes your profile, and when you are the workspace’s only member, all of its discovery data. Searches can be deleted individually from the sidebar." },
        { h2: "Reporting a vulnerability" },
        { p: "If you believe you have found a security issue, please report it through the [Contact page](/contact?topic=support) with the topic “Product support” and include steps to reproduce it. Please do not access other users’ data or disrupt the service while testing." },
      ],
    },
    ar: {
      title: "الأمان",
      summary: "كيف يحمي يولـياس حسابك ومساحة عملك والبيانات التي تكتشفها.",
      blocks: [
        { h2: "تسجيل دخول بدون كلمات مرور" },
        { p: "يستخدم يولـياس روابط الدخول بالبريد أو حساب Google بدل كلمات المرور، فلا توجد كلمة مرور يمكن تكرارها أو سرقتها أو تسريبها. يعمل كل رابط مرة واحدة وتنتهي صلاحيته بعد ساعة. ويمكنك تفعيل المصادقة الثنائية بتطبيق مصادقة، ومن الإعدادات ← الحساب تسجيل الخروج من كل الأجهزة دفعة واحدة." },
        { h2: "عزل مساحات العمل" },
        { p: "كل بحث وحملة وشركة وعميل محتمل ينتمي إلى مساحة عمل. تسمح قواعد الأمان على مستوى الصفوف في قاعدة البيانات بالوصول لأعضاء تلك المساحة فقط، وتطبّقها قاعدة البيانات نفسها وليس التطبيق وحده." },
        { h2: "الأدوار" },
        { ul: [
          "**المالك** — يدير الخطة والفريق.",
          "**المسؤول** — يدعو الأعضاء ويزيلهم ويدير الخطة.",
          "**العضو** — يعمل على عمليات البحث والحملات والعملاء المحتملين.",
        ] },
        { h2: "حماية البيانات" },
        { ul: [
          "كل الاتصالات مع يولـياس مشفرة أثناء النقل باستخدام TLS.",
          "تُخزن البيانات لدى مزود قاعدة البيانات مشفرة أثناء التخزين.",
          "المفاتيح ذات الصلاحيات العالية تُستخدم على الخادم فقط ولا تصل إلى المتصفح.",
          "الملفات المرفقة بالبحث تُقرأ لفهمه ولا تُخزن.",
          "بيانات البطاقة تُدخل في صفحة مزود الدفع ولا تصل إلى يولـياس أبدًا.",
          "نراقب الأخطاء لإصلاحها بسرعة، وتُحذف البيانات الشخصية والمفاتيح من تقاريرها.",
        ] },
        { h2: "طلبات الذكاء الاصطناعي" },
        { p: "تُرسل عمليات البحث إلى مزود الذكاء الاصطناعي فقط لإنتاج ملف عميلك المثالي. نرسل الحد الأدنى اللازم: الطلب ومرفقاته وسياق عملك." },
        { h2: "حذف البيانات" },
        { p: "حذف حسابك يحذف ملفك الشخصي، وإذا كنت العضو الوحيد في مساحة العمل يحذف كل بيانات الاكتشاف فيها. ويمكن حذف عمليات البحث واحدة تلو الأخرى من الشريط الجانبي." },
        { h2: "الإبلاغ عن ثغرة" },
        { p: "إذا اعتقدت أنك وجدت مشكلة أمنية، أبلغنا عبر [صفحة التواصل](/contact?topic=support) باختيار موضوع «دعم المنتج» مع خطوات إعادة إنتاجها. يُرجى عدم الوصول إلى بيانات مستخدمين آخرين أو تعطيل الخدمة أثناء الاختبار." },
      ],
    },
  },
};
