import type { Doc, Localized } from "./types";

// Legal pages. They describe how Yolias actually works today (magic-link
// sign-in, workspace isolation, AI processing, the cookies the app sets).
// Have them reviewed by counsel before accepting live payments.

export const LEGAL_UPDATED = "2026-10-06";
export const legalSlugs = ["privacy", "terms", "refunds", "cookies", "security"] as const;
export type LegalSlug = (typeof legalSlugs)[number];

export const legal: Record<LegalSlug, Localized<Doc>> = {
  privacy: {
    en: {
      title: "Privacy Policy",
      summary: "What Yolias collects, why, who processes it with us, and the choices you have.",
      blocks: [
        { h2: "Who we are" },
        { p: "Yolias is a customer-discovery product made by Taysonsta (“we”, “us”). This policy covers the Yolias website and app. For questions or requests, use the [Contact page](/contact)." },
        { h2: "Information we collect" },
        { h3: "Account and workspace" },
        { ul: [
          "Your email address, name and optional profile picture.",
          "Your company name, website and the description of what you sell, entered during onboarding.",
          "Preferences such as language, theme, text size, time zone, country and notification settings.",
          "Team membership, roles and invitations you send.",
        ] },
        { h3: "What you create in Yolias" },
        { ul: [
          "Searches you run, and the customer profile Yolias derives from them.",
          "Campaigns, their criteria and activity, and the companies and prospects they produce.",
          "Files you attach to a search are read to understand your request. We keep only their name and type, not their contents.",
        ] },
        { h3: "Business contact data about prospects" },
        { p: "Campaigns collect professional information about companies and their decision makers — such as name, job title, company, location and business contact channels — from the data sources Yolias connects to. Each record keeps the source it came from." },
        { h3: "Technical and usage data" },
        { p: "Sign-in events, IP address and browser information used to keep sessions secure, plus counts of discovery usage used for plan limits." },
        { h3: "Messages you send us" },
        { p: "What you submit through the Contact form, including your name, email, company and message." },
        { h2: "How we use information" },
        { ul: [
          "To provide the service: sign you in, run your searches and campaigns, and show your results.",
          "To apply plan limits, prevent abuse and keep accounts secure.",
          "To answer messages and support requests.",
          "To improve Yolias using aggregated usage, never by selling your data.",
        ] },
        { h2: "AI processing" },
        { p: "When you start a search, its text, any attachments and your business context are sent to our AI provider to produce the customer profile. The provider processes this data on our behalf to return the answer, under its commercial terms for business customers." },
        { h2: "Who processes data with us" },
        { table: { head: ["Provider role", "Purpose"], rows: [
          ["Database, authentication and file storage", "Hosting your workspace data, sign-in links and profile pictures"],
          ["AI model provider", "Understanding searches"],
          ["Email delivery", "Sending sign-in links and invitations"],
          ["Hosting", "Serving the website and app"],
          ["Payment provider (once billing is live)", "Processing subscription payments"],
        ] } },
        { p: "We do not sell personal information, and we do not share it for advertising." },
        { h2: "Retention and deletion" },
        { p: "We keep account and workspace data while your account is active. When you delete your account from Settings → Account, your profile is removed, and when you are the only member of your workspace, its searches, campaigns, companies and prospects are deleted with it. Contact messages are kept only as long as needed to handle them." },
        { h2: "Your rights" },
        { p: "Depending on where you live, you can ask to access, correct, export or delete your personal data, or object to certain processing. People whose business details appear in a Yolias campaign can make the same requests. Send them through the [Contact page](/contact) and we will respond within the time the law requires." },
        { h2: "Cookies" },
        { p: "Yolias uses a small number of essential and preference cookies, and no advertising cookies. The [Cookie Policy](/legal/cookies) lists each one." },
        { h2: "Changes" },
        { p: "If we change this policy in a meaningful way, we will update the date above and tell signed-in users in the app or by email." },
      ],
    },
    ar: {
      title: "سياسة الخصوصية",
      summary: "ما الذي يجمعه يولـياس، ولماذا، ومن يعالج البيانات معنا، والخيارات المتاحة لك.",
      blocks: [
        { h2: "من نحن" },
        { p: "يولـياس منتج لاكتشاف العملاء تقدمه Taysonsta («نحن»). تشمل هذه السياسة موقع يولـياس وتطبيقه. للأسئلة أو الطلبات استخدم [صفحة التواصل](/contact)." },
        { h2: "المعلومات التي نجمعها" },
        { h3: "الحساب ومساحة العمل" },
        { ul: [
          "بريدك الإلكتروني واسمك وصورتك الشخصية الاختيارية.",
          "اسم شركتك وموقعها ووصف ما تبيعه، كما أدخلتها أثناء الإعداد الأولي.",
          "تفضيلاتك مثل اللغة والمظهر وحجم النص والمنطقة الزمنية والدولة والإشعارات.",
          "عضوية الفريق والأدوار والدعوات التي ترسلها.",
        ] },
        { h3: "ما تنشئه داخل يولـياس" },
        { ul: [
          "عمليات البحث التي تجريها، وملف العميل المثالي الذي يستخرجه يولـياس منها.",
          "الحملات ومعاييرها ونشاطها، والشركات والعملاء المحتملون الناتجون عنها.",
          "الملفات التي ترفقها بالبحث تُقرأ لفهم طلبك فقط، ونحتفظ باسمها ونوعها دون محتواها.",
        ] },
        { h3: "بيانات التواصل المهنية للعملاء المحتملين" },
        { p: "تجمع الحملات معلومات مهنية عن الشركات وصنّاع القرار فيها — مثل الاسم والمسمى الوظيفي والشركة والموقع وقنوات التواصل المهنية — من مصادر البيانات التي يتصل بها يولـياس. ويحتفظ كل سجل بالمصدر الذي جاء منه." },
        { h3: "البيانات التقنية وبيانات الاستخدام" },
        { p: "أحداث تسجيل الدخول وعنوان IP ومعلومات المتصفح لتأمين الجلسات، إضافةً إلى أعداد الاستخدام لتطبيق حدود الخطط." },
        { h3: "الرسائل التي ترسلها لنا" },
        { p: "ما ترسله عبر نموذج التواصل، بما في ذلك اسمك وبريدك وشركتك ورسالتك." },
        { h2: "كيف نستخدم المعلومات" },
        { ul: [
          "لتقديم الخدمة: تسجيل دخولك، وتشغيل عمليات البحث والحملات، وعرض نتائجك.",
          "لتطبيق حدود الخطط ومنع إساءة الاستخدام وتأمين الحسابات.",
          "للرد على الرسائل وطلبات الدعم.",
          "لتحسين يولـياس باستخدام بيانات استخدام مجمّعة، دون بيع بياناتك أبدًا.",
        ] },
        { h2: "المعالجة بالذكاء الاصطناعي" },
        { p: "عند بدء بحث، يُرسل نصه ومرفقاته وسياق عملك إلى مزود الذكاء الاصطناعي لإنتاج ملف العميل المثالي. يعالج المزود هذه البيانات نيابةً عنا لإرجاع الإجابة، وفق شروطه التجارية لعملاء الأعمال." },
        { h2: "من يعالج البيانات معنا" },
        { table: { head: ["دور المزود", "الغرض"], rows: [
          ["قاعدة البيانات والمصادقة وتخزين الملفات", "استضافة بيانات مساحة العمل وروابط الدخول والصور الشخصية"],
          ["مزود نموذج الذكاء الاصطناعي", "فهم عمليات البحث"],
          ["إرسال البريد الإلكتروني", "إرسال روابط الدخول والدعوات"],
          ["الاستضافة", "تشغيل الموقع والتطبيق"],
          ["مزود الدفع (عند تفعيل الفوترة)", "معالجة مدفوعات الاشتراك"],
        ] } },
        { p: "لا نبيع المعلومات الشخصية، ولا نشاركها لأغراض إعلانية." },
        { h2: "الاحتفاظ والحذف" },
        { p: "نحتفظ ببيانات الحساب ومساحة العمل ما دام حسابك نشطًا. عند حذف حسابك من الإعدادات ← الحساب يُحذف ملفك الشخصي، وإذا كنت العضو الوحيد في مساحة العمل تُحذف معها عمليات البحث والحملات والشركات والعملاء المحتملون. ونحتفظ برسائل التواصل فقط بالقدر اللازم لمعالجتها." },
        { h2: "حقوقك" },
        { p: "بحسب مكان إقامتك، يمكنك طلب الوصول إلى بياناتك الشخصية أو تصحيحها أو تصديرها أو حذفها، أو الاعتراض على بعض أوجه المعالجة. ويحق للأشخاص الذين تظهر بياناتهم المهنية في حملات يولـياس تقديم الطلبات نفسها. أرسلها عبر [صفحة التواصل](/contact) وسنرد خلال المدة التي يحددها القانون." },
        { h2: "ملفات تعريف الارتباط" },
        { p: "يستخدم يولـياس عددًا محدودًا من ملفات تعريف الارتباط الأساسية وملفات التفضيلات، ولا يستخدم ملفات إعلانية. تجد كل ملف في [سياسة ملفات تعريف الارتباط](/legal/cookies)." },
        { h2: "التغييرات" },
        { p: "إذا غيّرنا هذه السياسة تغييرًا جوهريًا، سنحدّث التاريخ أعلاه ونبلغ المستخدمين المسجّلين داخل التطبيق أو عبر البريد." },
      ],
    },
  },
  terms: {
    en: {
      title: "Terms of Service",
      summary: "The agreement between you and Taysonsta for using Yolias.",
      blocks: [
        { h2: "Agreement" },
        { p: "By creating an account or using Yolias you agree to these terms on behalf of yourself and the organization you represent. Yolias is intended for business use." },
        { h2: "Your account" },
        { ul: [
          "You sign in with a magic link sent to your email; keep access to that inbox secure.",
          "The workspace owner and admins control who joins the workspace and which plan it uses.",
          "You are responsible for activity in your workspace.",
        ] },
        { h2: "Plans and billing" },
        { ul: [
          "Plans differ by monthly usage limits; every plan includes unlimited users.",
          "You can pay monthly or annually. The annual price is twelve times the monthly price and is charged upfront.",
          "Subscriptions renew at the end of each period until canceled. Prices exclude applicable taxes.",
          "Usage beyond your plan’s limits is not available until the next period, an upgrade or a purchase of extra prospects. Extra prospects don’t expire.",
          "Prices are in US dollars. Card payments are processed by our payment provider and charged in Egyptian pounds at the day’s exchange rate.",
          "Refunds follow the [Refund Policy](/legal/refunds).",
        ] },
        { h2: "Acceptable use" },
        { p: "You will not use Yolias to:" },
        { ul: [
          "send unsolicited bulk messages or contact people in ways that break anti-spam or data protection laws;",
          "collect data about individuals for purposes unrelated to legitimate business outreach;",
          "resell or publish prospect data as a standalone database;",
          "probe, overload or work around the security or limits of the service.",
        ] },
        { h2: "Prospect data and your obligations" },
        { p: "Yolias helps you discover businesses and professional contacts. How you use that information is your decision and your responsibility: you must have a lawful basis to contact people, honor opt-out requests, and follow the laws that apply to you and to them, such as personal data protection laws in Saudi Arabia, the UAE and the EU." },
        { h2: "AI output" },
        { p: "Customer profiles, match scores and enriched data are produced automatically and can be incomplete or wrong. Review results before relying on them." },
        { h2: "Your content" },
        { p: "You own the searches, files and data you put into Yolias and the results you export. You give us permission to process them only to provide and secure the service." },
        { h2: "Our service" },
        { p: "Yolias, its software and brand belong to Taysonsta. We improve the product continuously and may change or retire features; when a change materially reduces what your plan includes, we will tell you in advance." },
        { h2: "Suspension and termination" },
        { p: "You can stop using Yolias and delete your account at any time. We may suspend or close accounts that break these terms or put other users at risk, and will tell you why where the law allows." },
        { h2: "Disclaimers and liability" },
        { p: "Yolias is provided “as is”. To the extent the law allows, we are not liable for indirect or consequential losses, and our total liability for any claim is limited to the fees you paid for Yolias in the twelve months before the claim." },
        { h2: "Changes to these terms" },
        { p: "We will post updated terms here with a new date and notify signed-in users of material changes. Continuing to use Yolias after that means you accept them." },
        { h2: "Contact" },
        { p: "Questions about these terms: [Contact page](/contact)." },
      ],
    },
    ar: {
      title: "شروط الخدمة",
      summary: "الاتفاق بينك وبين Taysonsta لاستخدام يولـياس.",
      blocks: [
        { h2: "الاتفاق" },
        { p: "بإنشاء حساب أو استخدام يولـياس فإنك توافق على هذه الشروط عن نفسك وعن الجهة التي تمثلها. يولـياس مخصص للاستخدام التجاري." },
        { h2: "حسابك" },
        { ul: [
          "تسجّل الدخول برابط سحري يُرسل إلى بريدك؛ حافظ على أمان الوصول إلى هذا البريد.",
          "يتحكم مالك مساحة العمل ومسؤولوها في من ينضم إليها وفي الخطة المستخدمة.",
          "أنت مسؤول عن النشاط الذي يتم داخل مساحة عملك.",
        ] },
        { h2: "الخطط والفوترة" },
        { ul: [
          "تختلف الخطط في حدود الاستخدام الشهرية، وتشمل كل خطة مستخدمين غير محدودين.",
          "يمكنك الدفع شهريًا أو سنويًا. السعر السنوي يساوي اثني عشر ضعف السعر الشهري ويُدفع مقدمًا.",
          "يتجدد الاشتراك في نهاية كل فترة حتى إلغائه. الأسعار لا تشمل الضرائب المطبقة.",
          "لا يتوفر استخدام يتجاوز حدود خطتك حتى الفترة التالية أو الترقية أو شراء عملاء محتملين إضافيين. العملاء المحتملون الإضافيون لا تنتهي صلاحيتهم.",
          "الأسعار بالدولار الأمريكي. تُعالج المدفوعات بالبطاقة عبر مزوّد الدفع وتُخصم بالجنيه المصري بسعر صرف اليوم.",
          "تخضع المبالغ المستردة لـ[سياسة الاسترداد](/legal/refunds).",
        ] },
        { h2: "الاستخدام المقبول" },
        { p: "لن تستخدم يولـياس من أجل:" },
        { ul: [
          "إرسال رسائل جماعية غير مرغوب فيها أو التواصل مع الأشخاص بطرق تخالف قوانين مكافحة الرسائل المزعجة أو حماية البيانات؛",
          "جمع بيانات عن الأفراد لأغراض لا تتعلق بالتواصل التجاري المشروع؛",
          "إعادة بيع بيانات العملاء المحتملين أو نشرها كقاعدة بيانات مستقلة؛",
          "اختبار أمان الخدمة أو إثقالها أو التحايل على حدودها.",
        ] },
        { h2: "بيانات العملاء المحتملين والتزاماتك" },
        { p: "يساعدك يولـياس على اكتشاف الشركات وجهات الاتصال المهنية. أما طريقة استخدامك لهذه المعلومات فقرارك ومسؤوليتك: يجب أن يكون لديك أساس قانوني للتواصل، وأن تحترم طلبات إلغاء الاشتراك، وأن تلتزم بالقوانين المطبقة عليك وعليهم، مثل قوانين حماية البيانات الشخصية في السعودية والإمارات والاتحاد الأوروبي." },
        { h2: "مخرجات الذكاء الاصطناعي" },
        { p: "ملفات العملاء ونسب التطابق والبيانات المُثراة تُنتج تلقائيًا وقد تكون ناقصة أو غير دقيقة. راجع النتائج قبل الاعتماد عليها." },
        { h2: "محتواك" },
        { p: "تملك عمليات البحث والملفات والبيانات التي تضعها في يولـياس والنتائج التي تصدّرها. وتمنحنا الإذن بمعالجتها فقط لتقديم الخدمة وتأمينها." },
        { h2: "خدمتنا" },
        { p: "يولـياس وبرمجياته وعلامته التجارية ملك لـ Taysonsta. نطوّر المنتج باستمرار وقد نغيّر بعض الميزات أو نوقفها؛ وإذا قلّل تغيير ما بشكل جوهري مما تشمله خطتك فسنبلغك مسبقًا." },
        { h2: "الإيقاف والإنهاء" },
        { p: "يمكنك التوقف عن استخدام يولـياس وحذف حسابك في أي وقت. وقد نوقف أو نغلق الحسابات التي تخالف هذه الشروط أو تعرّض المستخدمين الآخرين للخطر، وسنوضح السبب متى سمح القانون بذلك." },
        { h2: "إخلاء المسؤولية وحدودها" },
        { p: "يُقدَّم يولـياس «كما هو». وفي الحدود التي يسمح بها القانون، لا نتحمل مسؤولية الخسائر غير المباشرة أو التبعية، وتقتصر مسؤوليتنا الإجمالية عن أي مطالبة على الرسوم التي دفعتها مقابل يولـياس خلال الاثني عشر شهرًا السابقة للمطالبة." },
        { h2: "تغيير هذه الشروط" },
        { p: "سننشر الشروط المحدّثة هنا بتاريخ جديد ونبلغ المستخدمين المسجّلين بالتغييرات الجوهرية. واستمرارك في استخدام يولـياس بعد ذلك يعني قبولك لها." },
        { h2: "التواصل" },
        { p: "للأسئلة حول هذه الشروط: [صفحة التواصل](/contact)." },
      ],
    },
  },
  refunds: {
    en: {
      title: "Refund Policy",
      summary: "When you can get your money back for a Yolias plan or extra prospects, and how.",
      blocks: [
        { h2: "Summary" },
        { p: "You can cancel any time from Settings → Billing; your plan stays active until the end of the period you paid for. If something went wrong with a payment, or you paid and didn’t use what you bought, ask us within 7 days and we will refund it." },
        { h2: "Subscriptions" },
        { ul: [
          "First payment or renewal: a full refund if you ask within 7 days of the payment and no prospects were delivered in that period.",
          "If prospects were delivered in that period, the payment is not refundable, but you can cancel so the plan doesn’t renew.",
          "Annual plans: within 7 days of the payment under the same condition; after that, the plan stays active until the end of the year.",
          "Renewals are never charged automatically: a renewal is paid only when you pay its invoice.",
        ] },
        { h2: "Extra prospects" },
        { ul: [
          "A pack is refundable within 7 days of the purchase if none of its prospects were used.",
          "Prospects that were used are not refundable. Extra prospects don’t expire, so there is no refund for unused time.",
        ] },
        { h2: "Always refunded" },
        { ul: [
          "Duplicate charges, or a charge for something you didn’t receive because of an error on our side.",
          "A charge made after you canceled, for the period after the cancellation.",
        ] },
        { h2: "How to ask" },
        { p: "Send a request through the [Contact page](/contact?topic=sales) from the workspace’s owner or admin email, with the invoice number. We answer within 3 business days." },
        { h2: "How refunds are paid" },
        { p: "Refunds go back to the card used for the payment through our payment provider, usually within 5–14 business days depending on your bank. Prices are in US dollars; if your card was charged in Egyptian pounds, the refund is the amount charged, and your bank’s exchange rate may make it differ slightly. A refunded payment’s invoice is voided, and the plan or prospects it paid for are removed." },
        { h2: "Changes" },
        { p: "We may update this policy; the date at the top shows the latest version. Payments made before a change follow the policy in force when they were made." },
      ],
    },
    ar: {
      title: "سياسة الاسترداد",
      summary: "متى يمكنك استرداد ما دفعته مقابل خطة يولـياس أو العملاء المحتملين الإضافيين، وكيف.",
      blocks: [
        { h2: "باختصار" },
        { p: "يمكنك الإلغاء في أي وقت من الإعدادات ← الفوترة، وتبقى خطتك فعّالة حتى نهاية الفترة المدفوعة. إذا حدثت مشكلة في الدفع، أو دفعت ولم تستخدم ما اشتريته، اطلب الاسترداد خلال 7 أيام وسنعيد المبلغ." },
        { h2: "الاشتراكات" },
        { ul: [
          "الدفعة الأولى أو التجديد: استرداد كامل إذا طلبته خلال 7 أيام من الدفع ولم يُسلَّم أي عميل محتمل في تلك الفترة.",
          "إذا سُلِّم عملاء محتملون في تلك الفترة فلا يُسترد المبلغ، ويمكنك الإلغاء حتى لا تتجدد الخطة.",
          "الخطط السنوية: خلال 7 أيام من الدفع بالشرط نفسه، وبعد ذلك تبقى الخطة فعّالة حتى نهاية السنة.",
          "لا يُخصم التجديد تلقائيًا أبدًا: يُدفع التجديد فقط عندما تدفع فاتورته.",
        ] },
        { h2: "العملاء المحتملون الإضافيون" },
        { ul: [
          "تُسترد الباقة خلال 7 أيام من الشراء إذا لم يُستخدم أي عميل محتمل منها.",
          "العملاء المحتملون المستخدمون لا يُستردون. والعملاء الإضافيون لا تنتهي صلاحيتهم، فلا يوجد استرداد مقابل وقت غير مستخدم.",
        ] },
        { h2: "يُسترد دائمًا" },
        { ul: [
          "الخصم المكرر، أو الخصم مقابل شيء لم تحصل عليه بسبب خطأ من جانبنا.",
          "أي خصم تم بعد إلغائك، عن الفترة التي تلي الإلغاء.",
        ] },
        { h2: "كيف تطلب الاسترداد" },
        { p: "أرسل طلبك عبر [صفحة التواصل](/contact?topic=sales) من بريد مالك مساحة العمل أو المسؤول، مع رقم الفاتورة. نرد خلال 3 أيام عمل." },
        { h2: "كيف يُعاد المبلغ" },
        { p: "يُعاد المبلغ إلى البطاقة المستخدمة في الدفع عبر مزوّد الدفع، عادةً خلال 5–14 يوم عمل حسب البنك. الأسعار بالدولار الأمريكي؛ وإذا خُصم المبلغ من بطاقتك بالجنيه المصري، يُعاد المبلغ المخصوم نفسه، وقد يختلف قليلاً بسبب سعر صرف البنك. تُلغى فاتورة الدفعة المستردة، وتُزال الخطة أو العملاء المحتملون الذين دُفعت مقابلها." },
        { h2: "التغييرات" },
        { p: "قد نحدّث هذه السياسة، ويوضح التاريخ في أعلى الصفحة آخر إصدار. تخضع المدفوعات السابقة لأي تغيير للسياسة السارية وقت الدفع." },
      ],
    },
  },
  cookies: {
    en: {
      title: "Cookie Policy",
      summary: "The cookies Yolias sets, what each one does and how long it lasts.",
      blocks: [
        { h2: "Our approach" },
        { p: "Yolias uses only the cookies it needs to sign you in and remember a few choices. There are no advertising or cross-site tracking cookies." },
        { h2: "Cookies we set" },
        { table: { head: ["Cookie", "Type", "Purpose", "Duration"], rows: [
          ["sb-…-auth-token", "Essential", "Keeps you signed in after you open a magic link", "Until you sign out or the session expires"],
          ["yolias_locale", "Preference", "Remembers Arabic or English", "1 year"],
          ["yolias_plan, yolias_period", "Essential", "Remember the plan and billing period you chose on Pricing until checkout", "30 days, removed after checkout"],
          ["yolias_sidebar", "Preference", "Remembers whether the app sidebar is open", "1 year"],
        ] } },
        { h2: "Managing cookies" },
        { p: "You can delete cookies in your browser settings at any time. Removing the essential sign-in cookie signs you out; removing preference cookies resets your language and layout choices." },
        { h2: "Changes" },
        { p: "If we add a cookie, it will appear in this table before it is used." },
      ],
    },
    ar: {
      title: "سياسة ملفات تعريف الارتباط",
      summary: "ملفات تعريف الارتباط التي يضعها يولـياس، ووظيفة كل منها، ومدتها.",
      blocks: [
        { h2: "نهجنا" },
        { p: "يستخدم يولـياس فقط ملفات تعريف الارتباط اللازمة لتسجيل دخولك وتذكّر بعض اختياراتك. لا توجد ملفات إعلانية أو ملفات تتبع عبر المواقع." },
        { h2: "الملفات التي نستخدمها" },
        { table: { head: ["الملف", "النوع", "الغرض", "المدة"], rows: [
          ["sb-…-auth-token", "أساسي", "يبقيك مسجّل الدخول بعد فتح الرابط السحري", "حتى تسجيل الخروج أو انتهاء الجلسة"],
          ["yolias_locale", "تفضيلات", "يتذكر اختيارك بين العربية والإنجليزية", "سنة واحدة"],
          ["yolias_plan, yolias_period", "أساسي", "يتذكر الخطة وفترة الفوترة التي اخترتها في صفحة الأسعار حتى الاشتراك", "30 يومًا، ويُحذف بعد الاشتراك"],
          ["yolias_sidebar", "تفضيلات", "يتذكر ما إذا كان الشريط الجانبي مفتوحًا", "سنة واحدة"],
        ] } },
        { h2: "إدارة الملفات" },
        { p: "يمكنك حذف ملفات تعريف الارتباط من إعدادات المتصفح في أي وقت. حذف ملف تسجيل الدخول يخرجك من حسابك، وحذف ملفات التفضيلات يعيد إعدادات اللغة والتخطيط." },
        { h2: "التغييرات" },
        { p: "إذا أضفنا ملفًا جديدًا فسيظهر في هذا الجدول قبل استخدامه." },
      ],
    },
  },
  security: {
    en: {
      title: "Security",
      summary: "How Yolias protects your account, your workspace and the data you discover.",
      blocks: [
        { h2: "Sign-in without passwords" },
        { p: "Yolias uses magic links instead of passwords, so there is no password to reuse, phish or leak. Each link works once and expires after one hour. From Settings → Account you can sign out of every device at once." },
        { h2: "Workspace isolation" },
        { p: "Every search, campaign, company and prospect belongs to a workspace. Database row-level security rules allow access only to members of that workspace, and they are enforced by the database itself, not only by the app." },
        { h2: "Roles" },
        { ul: [
          "**Owner** — manages the plan and the team.",
          "**Admin** — invites and removes members, manages the plan.",
          "**Member** — works with searches, campaigns and prospects.",
        ] },
        { h2: "Data protection" },
        { ul: [
          "All traffic to Yolias is encrypted in transit with TLS.",
          "Data is stored with our database provider, encrypted at rest.",
          "Privileged keys are used only on the server and never reach the browser.",
          "Files attached to a search are read to understand it and are not stored.",
        ] },
        { h2: "AI requests" },
        { p: "Searches are sent to our AI provider only to produce your customer profile. We send the minimum needed: the request, its attachments and your business context." },
        { h2: "Deleting data" },
        { p: "Deleting your account removes your profile, and when you are the workspace’s only member, all of its discovery data. Searches can be deleted individually from the sidebar." },
        { h2: "Reporting a vulnerability" },
        { p: "If you believe you have found a security issue, please report it through the [Contact page](/contact?topic=support) with the topic “Product support” and include steps to reproduce it. Please do not access other users’ data or disrupt the service while testing." },
      ],
    },
    ar: {
      title: "الأمان",
      summary: "كيف يحمي يولـياس حسابك ومساحة عملك والبيانات التي تكتشفها.",
      blocks: [
        { h2: "تسجيل دخول بدون كلمات مرور" },
        { p: "يستخدم يولـياس الروابط السحرية بدل كلمات المرور، فلا توجد كلمة مرور يمكن تكرارها أو سرقتها أو تسريبها. يعمل كل رابط مرة واحدة وتنتهي صلاحيته بعد ساعة. ومن الإعدادات ← الحساب يمكنك تسجيل الخروج من كل الأجهزة دفعة واحدة." },
        { h2: "عزل مساحات العمل" },
        { p: "كل بحث وحملة وشركة وعميل محتمل ينتمي إلى مساحة عمل. تسمح قواعد الأمان على مستوى الصفوف في قاعدة البيانات بالوصول لأعضاء تلك المساحة فقط، وتطبّقها قاعدة البيانات نفسها وليس التطبيق وحده." },
        { h2: "الأدوار" },
        { ul: [
          "**المالك** — يدير الخطة والفريق.",
          "**المسؤول** — يدعو الأعضاء ويزيلهم ويدير الخطة.",
          "**العضو** — يعمل على عمليات البحث والحملات والعملاء المحتملين.",
        ] },
        { h2: "حماية البيانات" },
        { ul: [
          "كل الاتصالات مع يولـياس مشفرة أثناء النقل باستخدام TLS.",
          "تُخزن البيانات لدى مزود قاعدة البيانات مشفرة أثناء التخزين.",
          "المفاتيح ذات الصلاحيات العالية تُستخدم على الخادم فقط ولا تصل إلى المتصفح.",
          "الملفات المرفقة بالبحث تُقرأ لفهمه ولا تُخزن.",
        ] },
        { h2: "طلبات الذكاء الاصطناعي" },
        { p: "تُرسل عمليات البحث إلى مزود الذكاء الاصطناعي فقط لإنتاج ملف عميلك المثالي. نرسل الحد الأدنى اللازم: الطلب ومرفقاته وسياق عملك." },
        { h2: "حذف البيانات" },
        { p: "حذف حسابك يحذف ملفك الشخصي، وإذا كنت العضو الوحيد في مساحة العمل يحذف كل بيانات الاكتشاف فيها. ويمكن حذف عمليات البحث واحدة تلو الأخرى من الشريط الجانبي." },
        { h2: "الإبلاغ عن ثغرة" },
        { p: "إذا اعتقدت أنك وجدت مشكلة أمنية، أبلغنا عبر [صفحة التواصل](/contact?topic=support) باختيار موضوع «دعم المنتج» مع خطوات إعادة إنتاجها. يُرجى عدم الوصول إلى بيانات مستخدمين آخرين أو تعطيل الخدمة أثناء الاختبار." },
      ],
    },
  },
};
