// Copy for the public pricing page (from the Yolias pricing design), EN + AR.
// Only the signup form texts were adapted: the form now really creates an
// account (magic link) instead of a "request access" placeholder.

export type Lang = "en" | "ar";

export const pricingCopy = {
  en: {
    brandName: "Yolias", navProduct: "Product", navSolutions: "Solutions", navPricing: "Pricing", navResources: "Resources",
    signIn: "Sign In", openApp: "Open Yolias", tryYolias: "Try Yolias",
    heroEyebrow: "YOLIAS PRICING", heroTitle: "Simple pricing. Powerful AI.",
    heroCopy: "Everything your team needs to sell, manage customers, and support them — all in one place.",
    heroSupport: "Unlimited users on every plan. Upgrade when you need more usage.",
    philosophy: "Same Yolias. Unlimited users. More usage as you grow.",
    proName: "Yolias Pro", proPrice: "$20", growthName: "Yolias Growth", growthPrice: "$50", scaleName: "Yolias Scale", scalePrice: "$100",
    perMonth: "per month",
    proDescription: "For teams getting started with AI-powered sales and support.",
    growthDescription: "For growing teams that need more AI usage and automation.",
    scaleDescription: "For teams with high-volume sales and customer support.",
    recommended: "Recommended", sameFeatures: "Same core Yolias features", unlimitedUsers: "Unlimited users",
    limitedUsage: "Limited usage capacity", moreUsage: "More usage capacity", highUsage: "High usage capacity",
    unlimitedEveryPlan: "Unlimited users on every plan.", usageLimits: "“Usage limits” apply.", taxNotice: "Prices shown don’t include applicable tax",
    comparisonEyebrow: "ONE PLATFORM. THREE USAGE LEVELS.", comparisonTitle: "Compare features across plans",
    comparisonCopy: "Every plan includes the full Yolias foundation. Choose the usage capacity that fits where your business is today.",
    feature: "Feature", coreFeatures: "Core features included on every plan", usageCapacity: "Usage capacity", included: "Included",
    aiSalesAgent: "AI Sales Agent", aiLeadGeneration: "AI Lead Generation", aiOutreach: "AI Outreach", aiFollowups: "AI Follow-ups",
    crm: "CRM", salesPipeline: "Sales Pipeline", leadManagement: "Lead Management", aiCustomerSupport: "AI Customer Support",
    websiteChatbot: "Website Chatbot", automations: "Automations", analytics: "Analytics", integrations: "Integrations",
    unlimitedUsersTable: "Unlimited Users", aiActions: "AI Actions", aiSalesOutreach: "AI Sales Outreach",
    customerConversations: "Customer Conversations", aiSupportConversations: "AI Support Conversations", automationRuns: "Automation Runs",
    limited: "Limited", more: "More", high: "High",
    faqEyebrow: "QUESTIONS, ANSWERED", faqTitle: "Frequently asked questions",
    faq: [
      ["Are users unlimited?", "Yes. Every Yolias plan includes unlimited users. You don’t pay per user."],
      ["What’s the difference between the plans?", "All plans include the same core Yolias features. The main difference is the amount of usage included in each plan."],
      ["Can I upgrade my plan?", "Yes. You can upgrade whenever your business needs more usage."],
      ["Can I use Yolias for sales and customer support?", "Yes. Yolias combines AI Sales, CRM, and AI Customer Support in one platform."],
      ["Are taxes included in the displayed prices?", "No. Prices shown don’t include applicable tax."],
      ["What happens when I reach my usage limit?", "Your usage is subject to the limits of your plan. You can upgrade to a higher plan when you need more capacity."],
    ] as [string, string][],
    finalEyebrow: "YOLIAS", finalTitle: "Ready to run your business with AI?",
    finalCopy: "Bring sales, customer management, and support together with Yolias.",
    formTitle: "Start your Yolias journey",
    formIntro: "Create your account with your work email. We’ll send you a magic link to sign in — no password needed.",
    nameLabel: "Full name", emailLabel: "Work email", companyLabel: "Company", submitIntent: "Create account",
    loading: "Sending your sign-in link…", validationError: "Please complete all fields using a valid work email.",
    sent: "Check your email — we sent a sign-in link to {email}.",
    privacyNotice: "Privacy policy is not connected on this preview page. Add the production policy URL before publishing.",
    termsNotice: "Terms are not connected on this preview page. Add the production terms URL before publishing.",
    footerTagline: "One connected operating system for sales, support, and growth.",
    resources: "Resources", helpCenter: "Help Center", documentation: "Documentation", faqLink: "FAQ", blog: "Blog", contactSupport: "Contact Support",
    company: "Company", about: "About", careers: "Careers", contact: "Contact", taysonsta: "Taysonsta",
    legal: "Legal", privacy: "Privacy Policy", terms: "Terms", cookies: "Cookies", security: "Security",
    copyright: "© 2026 Yolias. All rights reserved.",
    title: "Yolias — Simple pricing. Powerful AI.",
  },
  ar: {
    brandName: "Yolias", navProduct: "المنتج", navSolutions: "الحلول", navPricing: "الأسعار", navResources: "الموارد",
    signIn: "تسجيل الدخول", openApp: "افتح يولـياس", tryYolias: "جرّب يولـياس",
    heroEyebrow: "أسعار يولـياس", heroTitle: "أسعار بسيطة. ذكاء اصطناعي قوي.",
    heroCopy: "كل ما يحتاجه فريقك للبيع وإدارة العملاء ودعمهم — في مكان واحد.",
    heroSupport: "مستخدمون غير محدودين في كل خطة. قم بالترقية عندما تحتاج إلى استخدام أكثر.",
    philosophy: "نفس يولـياس. مستخدمون غير محدودين. استخدام أكثر مع نموك.",
    proName: "يولـياس برو", proPrice: "$20", growthName: "يولـياس للنمو", growthPrice: "$50", scaleName: "يولـياس للتوسع", scalePrice: "$100",
    perMonth: "شهريًا",
    proDescription: "للفرق التي تبدأ باستخدام المبيعات والدعم المدعومين بالذكاء الاصطناعي.",
    growthDescription: "للفرق النامية التي تحتاج إلى استخدام وأتمتة أكثر للذكاء الاصطناعي.",
    scaleDescription: "للفرق ذات المبيعات الكبيرة ودعم العملاء عالي الحجم.",
    recommended: "موصى بها", sameFeatures: "نفس ميزات يولـياس الأساسية", unlimitedUsers: "مستخدمون غير محدودين",
    limitedUsage: "سعة استخدام محدودة", moreUsage: "سعة استخدام أكبر", highUsage: "سعة استخدام عالية",
    unlimitedEveryPlan: "مستخدمون غير محدودين في كل خطة.", usageLimits: "تُطبق «حدود الاستخدام».", taxNotice: "الأسعار المعروضة لا تشمل الضريبة المطبقة",
    comparisonEyebrow: "منصة واحدة. ثلاثة مستويات استخدام.", comparisonTitle: "قارن الميزات عبر الخطط",
    comparisonCopy: "تتضمن كل خطة أساس يولـياس الكامل. اختر سعة الاستخدام التي تناسب أعمالك اليوم.",
    feature: "الميزة", coreFeatures: "ميزات أساسية متضمنة في كل خطة", usageCapacity: "سعة الاستخدام", included: "متضمن",
    aiSalesAgent: "وكيل المبيعات بالذكاء الاصطناعي", aiLeadGeneration: "توليد العملاء المحتملين بالذكاء الاصطناعي", aiOutreach: "التواصل بالذكاء الاصطناعي",
    aiFollowups: "المتابعات بالذكاء الاصطناعي", crm: "إدارة علاقات العملاء", salesPipeline: "مسار المبيعات", leadManagement: "إدارة العملاء المحتملين",
    aiCustomerSupport: "دعم العملاء بالذكاء الاصطناعي", websiteChatbot: "روبوت محادثة الموقع", automations: "الأتمتة", analytics: "التحليلات",
    integrations: "التكاملات", unlimitedUsersTable: "مستخدمون غير محدودين", aiActions: "إجراءات الذكاء الاصطناعي",
    aiSalesOutreach: "تواصل المبيعات بالذكاء الاصطناعي", customerConversations: "محادثات العملاء", aiSupportConversations: "محادثات الدعم بالذكاء الاصطناعي",
    automationRuns: "مرات تشغيل الأتمتة", limited: "محدود", more: "أكثر", high: "عالٍ",
    faqEyebrow: "إجابات واضحة", faqTitle: "الأسئلة الشائعة",
    faq: [
      ["هل عدد المستخدمين غير محدود؟", "نعم. تتضمن كل خطة من يولـياس مستخدمين غير محدودين. لا تدفع مقابل كل مستخدم."],
      ["ما الفرق بين الخطط؟", "تتضمن كل الخطط ميزات يولـياس الأساسية نفسها. الفرق الرئيسي هو مقدار الاستخدام المتضمن في كل خطة."],
      ["هل يمكنني ترقية خطتي؟", "نعم. يمكنك الترقية متى احتاج عملك إلى استخدام أكثر."],
      ["هل يمكنني استخدام يولـياس للمبيعات ودعم العملاء؟", "نعم. يجمع يولـياس بين المبيعات بالذكاء الاصطناعي وإدارة علاقات العملاء ودعم العملاء بالذكاء الاصطناعي في منصة واحدة."],
      ["هل تشمل الأسعار المعروضة الضرائب؟", "لا. الأسعار المعروضة لا تشمل الضريبة المطبقة."],
      ["ماذا يحدث عندما أصل إلى حد الاستخدام؟", "يخضع استخدامك لحدود خطتك. يمكنك الترقية إلى خطة أعلى عندما تحتاج إلى سعة أكبر."],
    ] as [string, string][],
    finalEyebrow: "يولـياس", finalTitle: "هل أنت مستعد لإدارة أعمالك بالذكاء الاصطناعي؟",
    finalCopy: "اجمع المبيعات وإدارة العملاء والدعم معًا باستخدام يولـياس.",
    formTitle: "ابدأ رحلتك مع يولـياس",
    formIntro: "أنشئ حسابك ببريد العمل. سنرسل لك رابط دخول سحري — بدون كلمة مرور.",
    nameLabel: "الاسم الكامل", emailLabel: "بريد العمل الإلكتروني", companyLabel: "الشركة", submitIntent: "إنشاء حساب",
    loading: "جارٍ إرسال رابط الدخول…", validationError: "يرجى إكمال جميع الحقول باستخدام بريد عمل إلكتروني صالح.",
    sent: "تحقق من بريدك — أرسلنا رابط الدخول إلى {email}.",
    privacyNotice: "سياسة الخصوصية غير مرتبطة في صفحة المعاينة هذه. أضف رابط سياسة الإنتاج قبل النشر.",
    termsNotice: "الشروط غير مرتبطة في صفحة المعاينة هذه. أضف رابط شروط الإنتاج قبل النشر.",
    footerTagline: "نظام تشغيل واحد متصل للمبيعات والدعم والنمو.",
    resources: "الموارد", helpCenter: "مركز المساعدة", documentation: "التوثيق", faqLink: "الأسئلة الشائعة", blog: "المدونة", contactSupport: "تواصل مع الدعم",
    company: "الشركة", about: "عن يولـياس", careers: "الوظائف", contact: "تواصل معنا", taysonsta: "Taysonsta",
    legal: "قانوني", privacy: "سياسة الخصوصية", terms: "الشروط", cookies: "ملفات تعريف الارتباط", security: "الأمان",
    copyright: "© 2026 يولـياس. جميع الحقوق محفوظة.",
    title: "يولـياس — أسعار بسيطة. ذكاء اصطناعي قوي.",
  },
} as const;

export type PricingCopy = (typeof pricingCopy)[Lang];

export const coreFeatureKeys = [
  "aiSalesAgent", "aiLeadGeneration", "aiOutreach", "aiFollowups", "crm", "salesPipeline", "leadManagement",
  "aiCustomerSupport", "websiteChatbot", "WhatsApp", "Instagram", "Facebook", "automations", "analytics", "integrations", "unlimitedUsersTable",
] as const;

export const usageRowKeys = ["aiActions", "aiSalesOutreach", "customerConversations", "aiSupportConversations", "automationRuns"] as const;
