// Cloudflare entry point: the OpenNext app plus the Cron Trigger that runs
// the background job worker (POST /api/worker with WORKER_SECRET), the
// production counterpart of scripts/dev-worker.mjs.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

interface Env {
  WORKER_SECRET?: string;
  NEXT_PUBLIC_SITE_URL?: string;
}

const worker = {
  fetch: handler.fetch,

  async scheduled(_event: unknown, env: Env, ctx: { waitUntil(p: Promise<unknown>): void }) {
    if (!env.WORKER_SECRET) return;
    const url = `${(env.NEXT_PUBLIC_SITE_URL ?? "https://www.yolias.com").replace(/\/$/, "")}/api/worker`;
    const req = new Request(url, { method: "POST", headers: { authorization: `Bearer ${env.WORKER_SECRET}` } });
    ctx.waitUntil(handler.fetch(req, env, ctx));
  },
};

export default worker;
